Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2020-10, with the labels that each got.

#1013 Actualizacion del seeder para refinanciamientos
  database/seeds/LoanStructureSeeder.php
Labels: refactorize

#1027 Revisión del método para evaluar la sub modalidad (caso Refinanciamiento)
  app/Loan.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#1039 corrección de la adición de las nuevas sub modalidades, segun el reglamento ART 79
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
  database/seeds/LoanStructureSeeder.php
  resources/views/loan/contracts/short.blade.php
  storage/responses/affiliate/get_loan_modality.200.json
Labels: refactorize

#1041 evaluacion para refinanciamiento
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/reprogramming.blade.php
  routes/api.php
  storage/responses/loan/loan_evaluate.200.json
Labels: enhancement

#1045 Creacion de la tabla "sismu" para el almacenado de datos del Sistema SISMU
  database/migrations/2020_10_23_083301_create_sismu_table.php
Labels: database

#1047 actualizacion calculadora
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug

#1048 actualizacion calculadora2
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug

#1054 validacion de propiedad
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
Labels: enhancement

#1056 modificacion metodo para obtener la sub modalidad del afiliado
  app/Loan.php
Labels: refactorize

#1061 modificacion para obtener modalidad del afiliado por POST
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
  routes/api.php
Labels: refactorize

#1069 CRUD Datos Sismu
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
  app/Loan.php
  app/Sismu.php
  database/migrations/2020_10_23_083301_create_sismu_table.php
  resources/assets/js/components/affiliate/Dashboard.vue
  routes/api.php
  storage/responses/loan/show.200.json
Labels: enhancement

#1062 Visualizacion de datos hipotecarios (SpecificDataLoan)
  resources/assets/js/components/affiliate/Dashboard.vue
  resources/assets/js/components/loan/SpecificDataLoan.vue
  resources/assets/js/components/workflow/Add.vue
Labels: enhancement

#1078 actualizacion sismu
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#1084 adenda reprogramacion sismu y referencias personales en formularios
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/reprogramming.blade.php
  resources/views/loan/forms/request_form.blade.php
Labels: enhancement

#1087 Modificacion de contratos de Refinanciamiento Caso SISMU
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#1090 arreglo referencias personales
  resources/views/loan/forms/request_form.blade.php
Labels: bug

#1091 Uniformar y modificacion de nombres de las sub modalidades de Refinanciamiento
  database/seeds/LoanStructureSeeder.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  storage/responses/affiliate/get_loan_modality.200.json
Labels: refactorize

#1110 Modificacion del metoto get modality caso de reprogramacion PVT y SISMU
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
  database/seeds/LoanStructureSeeder.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
Labels: refactorize

#1112 tipos de respuestas
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/forms/request_form.blade.php
Labels: bug
