Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2020-11, with the labels that each got.

#1116 solicitud
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/forms/request_form.blade.php
Labels: bug

#1117 obtencion de mod reprogramacion
  app/Http/Requests/AffiliateForm.php
  app/Loan.php
Labels: bug, refactorize

#1123 Se agrego la validación a la obtención de modalidad
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Requests/AffiliateForm.php
Labels: bug, enhancement

#1129 correccion metodo get_modalities bug
  app/Loan.php
Labels: bug, enhancement

#1148 Validacion de datos del Personal de Referencia
  app/Http/Controllers/Api/V1/PersonalReferenceController.php
  app/Http/Requests/PersonalReferenceForm.php
  database/migrations/2019_10_31_084036_create_personal_reference_table.php
Labels: refactorize, validation

#1151 Validacion datos del Afiliado y Conyugue
  app/Http/Requests/AffiliateForm.php
  app/Http/Requests/SpouseForm.php
Labels: refactorize, validation

#1162 liquido para calificacion
  app/Http/Controllers/Api/V1/CalculatorController.php
  routes/api.php
Labels: bug

#1164 liquido de subsistencia
  app/Http/Controllers/Api/V1/CalculatorController.php
  storage/responses/calculator/evaluate_guarantor.200.json
Labels: enhancement

#1179 ajustes metodo modalidades
  app/Loan.php
Labels: refactorize

#1194 obtener modalidad Cpop caso refi y repro
  app/Loan.php
Labels: bug, refactorize

#1195 Validación de datos requeridos para refi
  app/Http/Requests/LoanForm.php
Labels: validation

#1201 mensaje de afiliado no califica con modalidaa
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#1203 ajuste modalities
  app/Loan.php
Labels: refactorize

#1208 ajuste modalidades afili
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
Labels: refactorize

#1213 corrección validación de dirección requerido
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize, validation

#1214 validacion
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: enhancement

#1237 Validacion del campo requerido para pasivo del ente gestor y obtencion de modlidad de afp del campo pension_entity
  app/Http/Requests/AffiliateForm.php
  app/Loan.php
Labels: refactorize, validation
