Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2020-12, with the labels that each got.

#1282 CRUD PAGOS
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Requests/LoanPaymentForm.php
  app/LoanPayment.php
  config/translations.php
  database/migrations/2020_12_03_102607_add_colums_to_loan_payments.php
  storage/responses/loan/get_payments.200.json
  storage/responses/loan/set_payment.200.json
  storage/responses/loan_payment/show.200.json
  storage/responses/loan_payment/update.200.json
  storage/responses/voucher/destroy.200.json
Labels: database, refactorize, validation

#1299 Tags de prestamos de reprogramacion/refinanciamiento y correccion validacion del LoanForm
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
  database/seeds/TagSeeder.php
Labels: refactorize, validation

#1306 Correccion loan form
  app/Http/Requests/LoanForm.php
Labels: bug

#1325 Correccion de loanPayment
  app/Http/Requests/LoanPaymentForm.php
Labels: refactorize

#1330 modificación de migraciones loan Payment
  app/Http/Requests/LoanPaymentForm.php
  database/migrations/2019_11_03_102606_create_amortization_types_table.php
  database/migrations/2019_11_04_093204_create_loan_payments_table.php
  database/migrations/2020_12_03_102607_add_colums_to_loan_payments.php
Labels: database, refactorize

#1332 Importacion de datos de Comando y Senasir
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Imports/LoanPaymentImport.php
  routes/api.php
Labels: enhancement, validation

#1340 documentacion importation loan payment
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  storage/responses/loan_payment/importation_payments.200.json
Labels: documentation, enhancement

#1341 ajuste correccion metodo importacion Comand Senasir
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#1345 modificacion de fechas del affiliate y spouse
  resources/assets/js/components/affiliate/Profile.vue
  resources/assets/js/components/affiliate/Spouse.vue
Labels: refactorize

#1346 se adiciono el procedure id en el guardado de tesorería
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/payment/Steps.vue
Labels: enhancement

#1367 Reporte xls de prestamos en mora y bug de actualizacion de desembolso de prestamo
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Requests/LoanForm.php
  app/Loan.php
  routes/api.php
Labels: bug, enhancement, refactorize

#1368 correccion de bug al actualizar el la fecha de desembolso
  app/Http/Requests/LoanForm.php
Labels: bug

#1381 Bug reporte mora
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug, refactorize

#1385 Prestamos en mora los dias de penal, modificacion metodo
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Loan.php
Labels: refactorize
