Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2021-06, with the labels that each got.

#2291 bug exportacion de cobros
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#2289 nuevos calculos
  app/Console/Kernel.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Requests/LoanForm.php
  app/Loan.php
  app/LoanInterest.php
  database/migrations/2019_10_31_084035_create_loans_table.php
Labels: refactorize

#2293 cambio garante a titular
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  routes/api.php
  storage/responses/loan/switch_guarantor_lender.200.json
Labels: enhancement

#2294 modificacion de cartera
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: enhancement

#2295 Modificacion d formateo en calificacion y kardexs
  resources/views/loan/forms/qualification_form.blade.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: refactorize

#2297 Migraciones de categorías del loan payment, periodos
  database/migrations/2019_11_01_110455_create_loan_payment_categories_table.php
  database/migrations/2021_05_19_163556_create_periods_table.php
Labels: database

#2299 Creación de las tablas import payments, payment_groupeds, import_payment_groupeds para la importación
  database/migrations/2021_05_31_175109_create_import_payments_table.php
  database/migrations/2021_05_31_175359_create_payment_groupeds_table.php
  database/migrations/2021_06_01_113625_create_import_payment_groupeds_table.php
Labels: enhancement

#2296 Se agrego validacion en el indice de endeudamiento del garante al editar
  resources/assets/js/components/loan/SpecificDataLoan.vue
Labels: bug

#2302 Reporte de mora adicion de info y anticipos contrato
  app/Affiliate.php
  app/Exports/SheetExportPayment.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  database/migrations/2019_11_01_110455_create_loan_payment_categories_table.php
  database/migrations/2021_05_19_163556_create_periods_table.php
  resources/views/loan/contracts/advance.blade.php
Labels: enhancement, refactorize

#2304 Modificacion del reporte de desembolsados
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2307 Creacion de tablas loan payment, categorias y guardado del cobro y pe…
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentCategorieController.php
  app/Http/Controllers/Api/V1/PeriodController.php
  app/Http/Requests/LoanPaymentForm.php
  app/Http/Requests/PeriodForm.php
  app/LoanPayment.php
  app/LoanPaymentCategorie.php
  app/Period.php
  database/migrations/2019_11_01_110455_create_loan_payment_categories_table.php
  database/migrations/2019_11_04_093204_create_loan_payments_table.php
  database/seeds/LoanPaymentCategorieSeeder.php
  database/seeds/LoanStateSeeder.php
  database/seeds/ProcedureAmortizationSeeder.php
  routes/api.php
  storage/responses/loan/set_payment.200.json
  storage/responses/loan_payment_categorie/get_categorie_user.200.json
  storage/responses/periods/index.200.json
  storage/responses/periods/show.200.json
  storage/responses/periods/store.200.json
  storage/responses/report_loans/loan_desembolsado.200.json
  storage/responses/reports_amortizations/dincuent_cash_deposit.200.json
  storage/responses/reports_amortizations/dincuent_months_t_g.200.json
  storage/responses/reports_amortizations/report_amortization_pending.200.json
  version-seeder.sh
Labels: database, enhancement, refactorize

#2309 Cambio de flujo de trabajo y descripción de áreas de las diferentes modalidades en los seeders
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/RoleSequenceSeeder.php
Labels: refactorize

#2312 abreviatura tit gar
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#2311 se agrega campo a la tabla loan y loan_affiliate, también en el loanControler
  app/Http/Controllers/Api/V1/LoanController.php
  database/migrations/2019_10_31_084035_create_loans_table.php
  database/migrations/2019_11_01_094319_create_loan_affiliates_table.php
Labels: enhancement, refactorize

#2319 Añadir nuevo campo de amortización, cambio de cuota garante y código de pago
  resources/assets/js/components/affiliate/PersonalInformation.vue
  resources/assets/js/components/payment/Add.vue
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/payment/Steps.vue
Labels: enhancement

#2320 creación de tablas para fondo rotatorio
  database/migrations/2021_06_03_161137_create_fund_rotary_entries_table.php
  database/migrations/2021_06_03_162322_create_outputs_fund_rotatories_table.php
Labels: enhancement

#2321 Adicion de parametro de la modalidad para recibo fondo rotatorio
  app/LoanModalityParameter.php
  database/migrations/2019_11_29_112944_create_loan_modality_parameters_table.php
  database/seeds/LoanStructureSeeder.php
Labels: database

#2322 se argrega campo metodo para validar la edicion de un prestamo
  app/Loan.php
Labels: enhancement, refactorize

#2323 bug creacion de campo
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  database/migrations/2019_10_31_084035_create_loans_table.php
  database/migrations/2019_11_01_094319_create_loan_affiliates_table.php
Labels: bug

#2324 Indice calculado bug
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#2325 exportacion e importacion de cobros modificacion con categoria
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/LoanPayment.php
Labels: refactorize

#2328 correccion contrato
  app/Helpers/Util.php
Labels: enhancement

#2330 cambio de margenes de contrato
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2332 adicion de nombres del coronel y lazo contratos
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2337 Validación de fecha de contratos con el nuevo formato de dia/mes/año
  resources/assets/js/components/workflow/Add.vue
Labels: bug

#2335 Modificación de contratos de anticipos y cortos
  app/Helpers/Util.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: enhancement

#2340 ajuste del metodo edital para largo plazo
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: enhancement

#2343 se quito la validación del monto en el editar por parte del frontend
  resources/assets/js/components/loan/SpecificDataLoan.vue
Labels: bug

#2345 cambio de nombres de contratos
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#2346 visualización de monto préstamo padre en el re financiamiento
  resources/assets/js/components/loan/SpecificDataLoan.vue
  resources/assets/js/components/workflow/Add.vue
Labels: bug

#2348 Bug de indice de subsistencia
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug

#2350 contratos de corto plazo y largo plazo
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#2354 se realizo la habilitación del campo de comprobante en amortización
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/workflow/Dashboard.vue
Labels: bug

#2355 se realizo la modificación de los métodos de garante
  resources/assets/js/components/loan/Guarantor.vue
Labels: bug

#2356 garantias
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Requests/Guarantor_evaluateForm.php
Labels: bug

#2357 bug
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug

#2358 bug destroy
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#2359 se añadió el campo de monto de subsistencia en ballots result
  resources/assets/js/components/loan/BallotsResult.vue
Labels: bug

#2360 Corrección de bugs en largo plazo
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/Guarantor_evaluateForm.php
  resources/assets/js/components/loan/BallotsResult.vue
  resources/assets/js/components/loan/Guarantor.vue
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/workflow/Dashboard.vue
Labels: bug

#2361 MOdificacion de la la obt categoria
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#2362 cabio de fuente de texto del formulario de calificacion y solicitud
  resources/views/loan/forms/qualification_form.blade.php
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2363 permisos
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#2365 se realizo la validacion de certificacion presupuestaria
  resources/assets/js/components/workflow/Add.vue
Labels: bug

#2367 Seguimiento de prestamos
  app/Http/Controllers/Api/V1/LoanReportController.php
  routes/api.php
Labels: enhancement

#2366 Nuevo formulario de seguimiento
  resources/assets/js/components/tracing/Add.vue
  resources/assets/js/components/tracing/Dashboard.vue
  resources/assets/js/components/tracing/DocumentsFlow.vue
  resources/assets/js/components/tracing/FormTracing.vue
  resources/assets/js/components/tracing/ObserverFlow.vue
Labels: enhancement

#2373 Adicion de apellido de esposa
  app/Affiliate.php
Labels: refactorize

#2374 Code del préstamo para verificación
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: enhancement

#2376 Se agrega el campo disbursement_date_sismu para registro de fecha de desembolso préstamo sismu
  app/Http/Controllers/Api/V1/LoanController.php
  app/Sismu.php
  database/migrations/2020_10_23_083301_create_sismu_table.php
  database/migrations/2021_05_31_175359_create_payment_groupeds_table.php
  database/migrations/2021_06_03_161137_create_fund_rotary_entries_table.php
  database/migrations/2021_06_03_162322_create_outputs_fund_rotatories_table.php
  storage/responses/loan/update_sismu.200.json
Labels: refactorize

#2375 Contratos cambio de fecha al imprimible y adicion de info al Form de solicitud y modifi de formato kardex
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
  resources/views/loan/forms/request_form.blade.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: refactorize

#2377 se agrega el campo min_amount_fund_rotary en loan global parameter
  app/LoanGlobalParameter.php
  database/migrations/2019_11_06_094202_create_loan_global_parameters_table.php
  database/migrations/2021_05_31_175109_create_import_payments_table.php
  database/seeds/LoanGlobalParameterSeeder.php
Labels: refactorize

#2378 Adicion de fecha en lo contratos de tipo sismu en refis
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#2379 Fondo Rotatorio entrada crud version1
  app/FundRotaryEntry.php
  app/Http/Controllers/Api/V1/FundRotaryEntrieController.php
  app/Http/Requests/FundRotaryEntryForm.php
  routes/api.php
  storage/responses/fund_rotary_entry/destroy.200.json
  storage/responses/fund_rotary_entry/index.200.json
  storage/responses/fund_rotary_entry/show.200.json
  storage/responses/fund_rotary_entry/store.200.json
  storage/responses/fund_rotary_entry/update.200.json
Labels: database, enhancement, refactorize

#2380 CRUD fondo rotatorio V1
  app/Http/Controllers/Api/V1/OutputsFundRotatorieController.php
  app/Http/Requests/OutputsFundRotatorieForm.php
  app/Observers/OutputsFundRotatorieObserver.php
  app/OutputsFundRotatorie.php
  routes/api.php
  storage/responses/outputs_fund_rotatorie/destroy.200.json
  storage/responses/outputs_fund_rotatorie/index.200.json
  storage/responses/outputs_fund_rotatorie/show.200.json
  storage/responses/outputs_fund_rotatorie/store.200.json
  storage/responses/outputs_fund_rotatorie/update.200.json
Labels: enhancement

#2384 Creación del método para imprimir fondo rotatorio y formulario
  app/Http/Controllers/Api/V1/OutputsFundRotatorieController.php
  resources/views/loan/forms/disbursement_receipt_form.blade.php
  routes/api.php
Labels: enhancement

#2388 Adicion de apellido de casada de las esposas
  app/Spouse.php
Labels: refactorize

#2389 ajuste del tipo de renta del formulario de solicitud
  app/Http/Controllers/Api/V1/LoanController.php
  app/Spouse.php
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2395 ajuste del ingreso actualización del fondo rotatorio
  app/FundRotatory.php
  app/Http/Controllers/Api/V1/FundRotatoryController.php
  app/Http/Requests/FundRotatoryForm.php
  database/migrations/2021_06_15_083320_create_fund_rotatories_table.php
  routes/api.php
Labels: refactorize

#2396 cambio de validacion fondo rotatorio
  app/Http/Controllers/Api/V1/FundRotatoryController.php
  app/Http/Requests/FundRotatoryForm.php
Labels: refactorize

#2397 modificacion de la tabla fund_rotatory_ouputs.php
  app/Affiliate.php
  database/migrations/2021_06_03_162322_create_fund_rotatory_outputs_table.php
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2399 Ajuste en el registro de fondo rotatoria campo balance para el primer registro
  app/Http/Controllers/Api/V1/FundRotatoryController.php
Labels: refactorize

#2403 método para visualización del listado de entradas y salidas del fondo rotatorio fund_rotatory_entry_output
  app/FundRotatory.php
  app/FundRotatoryOutput.php
  app/Http/Controllers/Api/V1/FundRotatoryController.php
  routes/api.php
Labels: enhancement

#2404 Documentacion del metodo get_fund_rotatori_entry_output
  app/Http/Controllers/Api/V1/FundRotatoryController.php
  storage/responses/fund_rotary_entry/get_fund_rotatori_entry_output.200.json
Labels: enhancement

#2406 se agrega metodo register_advance_fund para el registro de salidas en anticipo
  app/FundRotatoryOutput.php
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#2407 se agrega afiliado y modalidad al metodo get_fund_rotatori_entry_output
  app/Http/Controllers/Api/V1/FundRotatoryController.php
Labels: enhancement

#2409 fondo rotatorio
  app/FundRotatory.php
  app/FundRotatoryOutput.php
  app/Http/Controllers/Api/V1/FundRotatoryController.php
  database/migrations/2021_06_03_161137_create_fund_rotary_entries_table.php
  database/migrations/2021_06_16_162322_create_fund_rotatory_outputs_table.php
Labels: bug

#2408 Se adiciono la validación de cuota sismu para el rehacer
  resources/assets/js/components/loan/Steps.vue
Labels: enhancement

#2416 recibo de pago de tesoreria anticipo
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/FundRotatoryOutputController.php
  resources/views/loan/forms/disbursement_receipt_form.blade.php
  resources/views/partials/header_treasury.blade.php
Labels: refactorize

#2417 ajuste del formato fuente y texto de desembolso para anticipo
  app/Helpers/Util.php
  resources/views/loan/forms/disbursement_receipt_form.blade.php
Labels: refactorize

#2418 bugs kardex
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: bug

#2420 cambio de redaccion del contrato de anticipo
  resources/views/loan/contracts/advance.blade.php
Labels: refactorize

#2421 cambio de texto
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#2423 Cambio de texto contrato anticipo
  resources/views/loan/contracts/advance.blade.php
Labels: refactorize

#2425 Crear método para el guardado de archivo .csv por FTP y creaccion de registros en la tabla period
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  routes/api.php
  storage/responses/loan_payment/upload_file_payment.200.json
Labels: enhancement

#2426 Development
  resources/assets/js/components/loan/SpecificDataLoan.vue
Labels: bug

#2428 se agrega paginado al listado de fondo rotatorio
  app/Http/Controllers/Api/V1/FundRotatoryController.php
Labels: refactorize

#2429 Cambio de fecha plan de pagos, adicion de informacion de sposa append loan
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: refactorize

#2427 se subsano las observaciones de formato de números en la amortización
  resources/assets/js/components/loan/SpecificDataLoan.vue
  resources/assets/js/components/payment/AddPayment.vue
Labels: bug

#2430 ajuste al formulario de calificacion
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#2432 migraciones
  database/migrations/2021_06_23_084000_create_import_command_payments_table.php
  database/migrations/2021_06_23_084110_create_import_senasir_payments_table.php
Labels: database

#2433 bug
  app/Http/Controllers/Api/V1/FundRotatoryController.php
Labels: bug

#2434 Migraciones de payments agrupados de commnad y senasir
  database/migrations/2021_05_31_175359_create_command_payment_groups_table.php
  database/migrations/2021_06_01_113625_create_import_payment_groupeds_table.php
  database/migrations/2021_06_23_095026_create_senasir_payment_groups_table.php
Labels: database

#2436 se agrega campos de estado a la tabla y modelo de periods
  app/Period.php
  database/migrations/2021_05_19_163556_create_periods_table.php
Labels: refactorize

#2443 Modificación del método de registro de periodo y validación
  app/Http/Controllers/Api/V1/PeriodController.php
  storage/responses/periods/store.200.json
Labels: enhancement

#2445 Modificación de contratos refinanciamiento corto plazo
  app/Http/Controllers/Api/V1/PeriodController.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#2450 dato global
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
  database/seeds/LoanGlobalParameterSeeder.php
Labels: bug

#2452 Agrupación de cobros
  app/Http/Controllers/Api/V1/ImportationController.php
  routes/api.php
  storage/responses/importation/importation_agroup.200.json
Labels: enhancement

#2453 ajuste del metodo upload_file_payment para cargado de archivo de impo…
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#2456 MOdificacion de registro con los campos create y update
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: enhancement

#2457 relacion del metodo upload_file_payment y el metodo copy_payments
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  routes/api.php
Labels: refactorize

#2461 Bug reportes
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: bug

#2460 closed #2458, closed #2459
  resources/assets/js/components/payment/ImportExportPayment.vue
  resources/assets/js/menu.json
  resources/assets/js/routes.js
Labels: enhancement

#2468 validacion a la secuencia en la creacion de periodos
  app/Http/Controllers/Api/V1/PeriodController.php
Labels: refactorize

#2469 bug creacion de perioodo
  app/Http/Controllers/Api/V1/PeriodController.php
Labels: bug

#2470 Modificacion metodo para el gardado de excel generado
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2471 metodo para descargar el archivo de descarga
  app/Http/Controllers/Api/V1/ImportationController.php
  routes/api.php
Labels: enhancement

#2475 copia de datos
  app/Http/Controllers/Api/V1/ImportationController.php
  app/LoanPayment.php
Labels: enhancement

#2478 Refrescar la visualización del nombre del mes en el periodo creado
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: bug

#2479 actualizacion next_payment
  app/Loan.php
Labels: bug

#2482 mandar el id del periodo al momento de validar los datos
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: bug

#2486 importacion de cobros senasir, metodo de borrado cuando este en estado false
  app/Http/Controllers/Api/V1/ImportationController.php
  routes/api.php
  storage/responses/importation/importation_senasir.200.json
  storage/responses/importation/rollback_copy_groups.200.json
Labels: enhancement

#2488 Se añadió el método de borrado de los datos agrupados cuando se cierra el popup sin que haga la importacion
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement

#2489 modificaciones y arreglos import senasir y documentacion de metodo co…
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/PeriodController.php
  storage/responses/importation/importation_command.200.json
Labels: documentation, refactorize

#2490 se añade variable de validacion
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2492 validacion
  app/Http/Controllers/Api/V1/ImportationController.php
  storage/responses/importation/importation_command.200.json
Labels: validation

#2493 ajuste de metodo test_guarantor para la validacion de categoria
  app/Affiliate.php
Labels: bug

#2495 quitar Validacion de la calle de direccion
  app/Http/Requests/AddressForm.php
Labels: validation

#2497 bug upload_file_payment
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: bug

#2499 reporte de amortizacion de cobros por periodo, documentacion y modifi…
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/ImportationReportController.php
  routes/api.php
  storage/responses/reports_amortizations/amortization_for_periods.200.json
Labels: enhancement

#2500 actualizar documentacion de periods
  storage/responses/periods/destroy.200.json
  storage/responses/periods/get_list_month.200.json
  storage/responses/periods/index.200.json
  storage/responses/periods/show.200.json
  storage/responses/periods/update.200.json
Labels: documentation

#2501 cambio de la devolucion de la respuesta de TIT y GAR a T y G
  app/Http/Controllers/Api/V1/ImportationReportController.php
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2504 importación de comando
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement

#2505 fecha de pago
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: bug

#2506 se corrigio el bug del popup
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement

#2508 añadiendo el loading en los botones de reporte
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement

#2509 ajuste en el metodo copy_payments para el copiado de archivo desde ftp
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2510 Correccion respuesta de importacion comando
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2512 Se añadió el loading en el botón de importar
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement

#2513 se renombra tabla periods por loan_payment_periods
  database/migrations/2021_05_19_163556_create_loan_payment_periods_table.php
Labels: refactorize

#2514 Cambio de nombre de las migraciones y tablas
  database/migrations/2021_05_31_175359_create_loan_payment_group_commands_table.php
  database/migrations/2021_06_23_095026_create_loan_payment_group_senasirs_table.php
Labels: database

#2517 renombrado de modeo, controlador y ruta de Period a LoanPaymentPeriod
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  app/LoanPaymentPeriod.php
  routes/api.php
Labels: refactorize

#2519 renombrar archivo PeriodForm por LoanPaymenPeriodForm
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  app/Http/Requests/LoanPaymentPeriodForm.php
Labels: refactorize

#2518 modificacion de archivos con nuevos nombres de las tablas
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/ImportationReportController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#2520 bug en validacion al renombrar en el metodo get_list_month
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
Labels: refactorize

#2521 validación del contenido del archivo en la importación
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2522 se quita amount_concilationdel modelo LoanPaymentPeriod
  app/LoanPaymentPeriod.php
Labels: refactorize

#2523 restricción de fechas menores a 15 del mes
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2528 cambio de nombre de carpetas y encabezado de los archivos de importacion
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize
