Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2021-07, with the labels that each got.

#2530 Cambio de títulos para el guardado de los PDF
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
  resources/views/loan/forms/qualification_form.blade.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: refactorize

#2531 cambio de orden de los prestamos
  app/Http/Controllers/Api/V1/ImportationController.php
  database/seeds/AdvanceRoleSeeder.php
Labels: refactorize

#2532 creacion de la migracion para adicionar el nuevo campo en el loan
  database/migrations/2021_07_03_221316_add_payment_plan_compliance_loans.php
Labels: database

#2533 obtencion de monto a pagar
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  routes/api.php
  storage/responses/loan/payment_amount.200.json
Labels: enhancement

#2534 cambios en la funcion de obtencion de mod
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
  storage/responses/loan/payment_amount.200.json
Labels: refactorize

#2537 bug imprimitr plan de pagos
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#2539 Adicion de campo de payment_plan_compliance en el loan
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  app/Loan.php
Labels: database

#2541 Adicion para actualizacion del nuevo campo del loan plan_payment_comp…
  app/Observers/LoanPaymentObserver.php
Labels: refactorize

#2543 creación de método para visualizar barra de progreso pasos de importación
  app/Http/Controllers/Api/V1/ImportationController.php
  routes/api.php
Labels: enhancement

#2544 next_payment
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: enhancement

#2545 Validación del nombre del archivo en la importación
  app/Http/Controllers/Api/V1/ImportationController.php
  storage/responses/loan_payment/import_progress_bar.200.json
Labels: refactorize

#2546 obtener pago
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: enhancement

#2547 modificacion importacion de senasir
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: refactorize

#2550 Se agrega nombre del archivo al método import_progress_bar
  app/Http/Controllers/Api/V1/ImportationController.php
  storage/responses/loan_payment/import_progress_bar.200.json
Labels: refactorize

#2553 plan de pagos e importacion
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Loan.php
  app/LoanPayment.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: enhancement

#2552 Importación de pagos
  resources/assets/js/components/payment/ImportExportPayment.vue
  resources/assets/js/menu.json
Labels: enhancement

#2559 liquidacion
  app/Loan.php
Labels: enhancement

#2561 Obtener monto a pagar al hacer una amortización directa
  resources/assets/js/components/payment/AddAmortization.vue
Labels: enhancement

#2563 agrupacion de cobros limpiar antes de agrupar
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2565 bug
  app/Loan.php
Labels: bug

#2567 quitado del editado de pasos en la importacion
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement

#2568 cobro de penalidad y dias de gracia
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Loan.php
Labels: refactorize

#2569 Arreglo de calculos en el desembolso report
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2571 agregar conteo de registros copiados y agrupados en el método import_progress_bar
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2574 reporte para la solicitud de descuentos
  app/Exports/FileWithMultipleSheetsReport.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2580 Bug de records actualizacion de prestamos
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanController.php
  config/translations.php
Labels: bug

#2581 reporte de prestamos simultaneos PVT SISMU
  app/Affiliate.php
  app/Exports/SheetExportPayment.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  routes/api.php
  storage/responses/report_loans/loan_desembolsado.200.json
Labels: enhancement

#2584 Reporte de prestamos para solicitud a SENASIR
  app/Http/Controllers/Api/V1/ImportationReportController.php
  routes/api.php
  storage/responses/reports_request_payments/request_senasir.200.json
Labels: enhancement

#2586 garantias sismu
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: enhancement

#2585 Adicion de cuotas del garante reporte de sol senasir
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2588 reporte de solicitud de pagos comando
  app/Http/Controllers/Api/V1/ImportationReportController.php
  routes/api.php
Labels: enhancement

#2589 Union de reportes de comando y senasir para la solicitud
  app/Http/Controllers/Api/V1/ImportationReportController.php
  routes/api.php
Labels: refactorize

#2590 cambio de nombre de la variable
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2591 comando importacion visualizacion de datos en el reporte
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: enhancement, refactorize

#2593 Estados de Solicitudes de Prestamos
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
  resources/views/loan/reports/request_state_report.blade.php
  routes/api.php
  storage/responses/loan/print_request_loans.200.json
Labels: enhancement

#2594 cambio de bariable
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2599 MOd redoondeo
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: refactorize

#2603 Se quita la visualización de categoría para afiliados pasivo de titular
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2600 Arreglo de bug contrato lar afp
  resources/views/loan/contracts/long.blade.php
Labels: bug

#2598 Adición de reportes de solicitud y cabecera de la importación
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement

#2609 visualización de datos de un garante en reporte de solicitud comando
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2613 Validacion
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
Labels: bug

#2614 Reporte de información para sol desglosado adición de información
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2616 Se agrega orden de las boletas en el formulario de calificacion
  app/Loan.php
Labels: refactorize

#2617 cambio de texto denominacion de titular a prestatario en titulo
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#2615 Observador de fondo rotatorio
  app/FundRotatory.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Observers/FundRotatoryObserver.php
  app/Providers/AppServiceProvider.php
  app/Providers/FundRotatoryServiceProvider.php
  app/Record.php
  config/app.php
  config/translations.php
Labels: enhancement

#2618 cambio de variables en el metodo report_request_comand_payments
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2619 reporte de desembolsados
  app/Exports/ArchivoPrimarioExport.php
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2621 visualización de datos en la observación del seguimiento
  resources/assets/js/components/tracing/Add.vue
  resources/assets/js/components/tracing/FormTracing.vue
  resources/assets/js/components/tracing/HistoryFlow.vue
  resources/assets/js/components/tracing/ObserverFlow.vue
Labels: enhancement

#2622 modificacion report
  app/Http/Controllers/Api/V1/LoanReportController.php
  database/migrations/2021_07_19_180738_add_affiliate_id_to_loans.php
  database/migrations/2021_07_19_180806_add_type_to_loan_affiliates.php
Labels: refactorize

#2630 guardado del loan
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/LoanPayment.php
Labels: refactorize

#2631 prestatario
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  storage/responses/loan/show.200.json
Labels: enhancement

#2633 modf migracion de loan affiliates type
  database/migrations/2021_07_19_180806_add_type_to_loan_affiliates.php
Labels: database

#2623 cambio de variable de disbursable_id con affiliate_id
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2634 garantes
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  storage/responses/loan/show.200.json
Labels: enhancement

#2636 completado de campos de la tabla loan_affiliates
  app/Loan.php
Labels: refactorize

#2637 iniciales esposa
  app/Loan.php
  app/Spouse.php
  storage/responses/loan/show.200.json
Labels: enhancement

#2638 garantes prestatarios
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  storage/responses/loan/show.200.json
Labels: bug

#2639 prestamos affiliado y esposa
  app/Affiliate.php
  app/Spouse.php
Labels: refactorize

#2640 grado
  app/Loan.php
Labels: enhancement

#2644 modificacion de prestatario
  app/Http/Controllers/Api/V1/FundRotatoryOutputController.php
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/VoucherController.php
  app/Http/Requests/LoanForm.php
  app/LoanPayment.php
  config/translations.php
  resources/views/flow/tbody/loan.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: refactorize

#2647 modificaciones
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
  app/Spouse.php
  storage/responses/loan/show.200.json
Labels: enhancement

#2654 se agrega campo type al método editar
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2656 Seguimiento de prestamos para listar el seguimiento por prestatario
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Http/Requests/SpouseForm.php
  storage/responses/loan/list_tracing.200.json
Labels: enhancement

#2657 generador de reportes de amortizaciones
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: enhancement

#2661 ajuste del método list_loan_generate para listado de prestamos vigentes y cancelados
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2662 actualizacion de documentacion del metodo list_loan_generate
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/loan_payment/list_loan_payment_generate.200.json
Labels: refactorize

#2663 Seguimiento del prestamo
  app/Http/Controllers/Api/V1/LoanReportController.php
  storage/responses/loan/list_tracing.200.json
Labels: refactorize

#2664 Ajuste en el metodo import_progress_bar para agregar periodo de importacion
  app/Http/Controllers/Api/V1/ImportationController.php
  storage/responses/loan_payment/import_progress_bar.200.json
Labels: refactorize

#2666 Reporte de informacion de nuevos y recurrentes para solicitud
  app/Exports/MultipleSheetsReport.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
Labels: refactorize

#2667 se agrega mas campos a los reportes de prestamos vigentes y cancelado
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/loan/list_loans_generate.200.json
Labels: refactorize

#2671 generador de reportes de pagos
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Loan.php
  storage/responses/loan_payment/list_loan_payment_generate.200.json
Labels: enhancement

#2672 creacion de la vista view_loan_borrower de prestamos
  database/migrations/2021_07_26_220728_create_view_loan_borrower_table.php
Labels: enhancement

#2678 full_name_affiliate
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/assets/js/plugins/echo.js
  storage/responses/loan_payment/list_loan_payment_generate.200.json
Labels: enhancement

#2682 cambio de texto de state_type
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#2683 evaluacion garante cpop
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug

#2685 Ajuste del reporte del listado de prestamos
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2687 cambio texto en la creacion de la vista view_loan_borrowe
  database/migrations/2021_07_26_220728_create_view_loan_borrower_table.php
Labels: refactorize

#2689 solicitud descuentos senasir
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: enhancement

#2690 COrreccion bug voucher
  app/Http/Controllers/Api/V1/VoucherController.php
Labels: bug

#2676 Correcciones en el modulo de seguimiento
  resources/assets/js/components/dashboard/DataLoanAffiliate.vue
  resources/assets/js/components/dashboard/DataLoanInformation.vue
  resources/assets/js/components/dashboard/Index.vue
  resources/assets/js/components/payment/Add.vue
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/payment/Steps.vue
  resources/assets/js/components/tracing/Add.vue
  resources/assets/js/components/tracing/Dashboard.vue
  resources/assets/js/components/tracing/DocumentsFlow.vue
  resources/assets/js/components/tracing/FormTracing.vue
  resources/assets/js/components/tracing/HistoryFlow.vue
  resources/assets/js/components/tracing/ObserverFlow.vue
  resources/assets/js/components/workflow/Add.vue
  resources/assets/js/components/workflow/SpecificDataLoan.vue
Labels: enhancement

#2695 modificacion de la vista borroguers guarantor
  database/migrations/2021_07_27_081457_create_view_borrower_guarantor_table.php
Labels: refactorize

#2696 modificacion de la vista view_loan_borrower
  database/migrations/2021_07_26_220728_create_view_loan_borrower_table.php
Labels: refactorize

#2698 REPORE DE EFECTIVO Y DEP EN CUENTA
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
Labels: refactorize

#2700 Reporte de pendienytes de amortizaciones
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
Labels: refactorize

#2701 Adicion de exp en report loan information y arreglo busqueda seg
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2702 reporte de mora
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: enhancement

#2704 Arreglo bug de imprecion de recibo fondo rotatorio
  app/Http/Controllers/Api/V1/FundRotatoryController.php
  app/Http/Controllers/Api/V1/FundRotatoryOutputController.php
Labels: bug

#2705 ajuste del reporte de descuento titular-garante
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
Labels: refactorize

#2699 Visualización de nombre de afiliado para prestamos hipotecario
  resources/assets/js/components/loan/Add.vue
  resources/assets/js/components/loan/BallotsResult.vue
  resources/assets/js/components/loan/BallotsResultHipotecary.vue
  resources/assets/js/components/loan/Guarantor.vue
  resources/assets/js/components/loan/LoanInformation.vue
  resources/assets/js/components/loan/Steps.vue
  resources/assets/js/components/payment/AddAmortization.vue
Labels: enhancement

#2719 estado de cartera
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
Labels: enhancement

#2722 correccion de bug observador payment
  app/Observers/LoanPaymentObserver.php
Labels: bug

#2714 se agrega campos a la vista view_loan_borrower
  database/migrations/2021_07_26_220728_create_view_loan_borrower_table.php
Labels: refactorize

#2723 modificación del reporte de prestamos amortizados mensualmente descuento por garantía
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2724 bug plan de pagos
  app/Loan.php
Labels: enhancement

#2726 Loading de los botones de importación
  resources/assets/js/components/loan/Guarantor.vue
  resources/assets/js/components/payment/ImportExport.vue
  resources/assets/js/components/payment/ImportExportPayment.vue
  resources/assets/js/components/tracing/Add.vue
  resources/assets/js/components/tracing/Dashboard.vue
  resources/assets/js/components/tracing/DocumentsFlow.vue
  resources/assets/js/components/tracing/FormTracing.vue
  resources/assets/js/routes.js
Labels: enhancement

#2730 console para migracion
  app/Console/Commands/LoanAffiliateUpdate.php
  app/Console/Commands/LoanUpdate.php
Labels: enhancement

#2728 plan de pagos
  app/Loan.php
Labels: refactorize

#2731 bug vista
  database/migrations/2021_07_26_220728_create_view_loan_amortizations_table.php
Labels: bug
