Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2021-09, with the labels that each got.

#2841 modificacion del resporte estado adicion de columna y estilo
  app/Http/Controllers/Api/V1/LoanReportController.php
  resources/views/loan/reports/request_state_report.blade.php
Labels: refactorize

#2842 adición validaciones fibdo rotatorio
  resources/assets/js/components/fund_rotary/ListEntry.vue
  resources/assets/js/components/tracing/ListTracingLoans.vue
  resources/assets/js/menu.json
Labels: enhancement, refactorize

#2843 cracion min_amount_fund_rotary para monto minimo del fondo rotatorio
  database/migrations/2019_11_06_094202_create_loan_global_parameters_table.php
  database/migrations/2021_09_01_084041_add_min_amount_fund_rotatory_loan_global_parameters_table.php
Labels: enhancement

#2844 correcion de report desembolso bug
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
Labels: bug

#2845 reporte amortizaciones
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
  resources/views/loan/reports/payments_in_treasury_report.blade.php
  routes/api.php
Labels: enhancement

#2846 report salidas desembolsos ajustes
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
Labels: refactorize

#2848 Adicion del dato matricula para pasivos form de solicitud requerimiento por ticket
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2847 Formulario de cobros manuales e importación.
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/payment/ImportExportPayment.vue
  resources/assets/js/components/payment/Steps.vue
Labels: enhancement

#2849 Observador de la tabla movimientos de fondo rotatorio
  app/MovementFundRotatory.php
  app/Observers/FundRotatoryObserver.php
  app/Observers/MovementFundRotatoryObserver.php
  app/Providers/AppServiceProvider.php
  app/Providers/MovementFundRotatoryServiceProvider.php
  app/Record.php
  config/app.php
Labels: enhancement

#2850 Observador de la movement concepts
  app/Http/Requests/MovementConceptForm.php
  app/Http/Requests/MovementFundRotatoryForm.php
  app/Observers/MovementConceptObserver.php
  app/Providers/AppServiceProvider.php
  app/Providers/MovementConceptServiceProvider.php
  app/Record.php
  config/app.php
Labels: enhancement

#2851 Se agrega datos de la boleta en detalle del prestamo
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: enhancement, refactorize

#2852 Condiciones para la visualización de información
  resources/assets/js/components/affiliate/Add.vue
  resources/assets/js/components/affiliate/Dashboard.vue
  resources/assets/js/components/dashboard/Index.vue
  resources/assets/js/plugins/common.js
  resources/assets/js/plugins/vuetify.js
Labels: bug, refactorize

#2854 limpieza consola y adicion de condiciones
  resources/assets/js/components/affiliate/Add.vue
  resources/assets/js/components/affiliate/Profile.vue
  resources/assets/js/components/dashboard/Index.vue
  resources/assets/js/components/payment/HistoryPayments.vue
  resources/assets/js/components/payment/Kardex.vue
  resources/assets/js/components/payment/List.vue
  resources/assets/js/components/tracing/ListTracingLoans.vue
  resources/assets/js/components/workflow/Add.vue
  resources/assets/js/components/workflow/AddObservation.vue
  resources/assets/js/components/workflow/Dashboard.vue
  resources/assets/js/components/workflow/DocumentsFlow.vue
  resources/assets/js/components/workflow/List.vue
Labels: bug, refactorize

#2853 cambio al formato del en la recuperacion de boletas en el formulario …
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#2855 Contratos adicion de codigo al footer aumento de tamaño al titulo, reduccion de espacion em las firmas, formato de hora de impresion
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Http/Controllers/Api/V1/VoucherController.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/reprogramming.blade.php
  resources/views/loan/contracts/short.blade.php
  resources/views/partials/footer.blade.php
Labels: refactorize

#2856 Eliminacion de migraciones de antiguo fondo rotatorio
  database/migrations/2021_06_15_083320_create_fund_rotatories_table.php
  database/migrations/2021_06_16_162322_create_fund_rotatory_outputs_table.php
  database/migrations/2021_08_25_173550_create_function_egress_fund_rotatory.php
Labels: refactorize

#2857 cambio de variable de rent payable_liquid
  app/Loan.php
Labels: refactorize

#2858 cambio de formato y variables del formulario de calificacion
  app/Loan.php
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#2859 se agrega validacion en el ingreso del fondo rotatorio
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
Labels: refactorize

#2860 cambio de variable del metodo ballot_affiliate
  app/Loan.php
  resources/views/loan/reports_tesoreria/cash_report.blade.php
Labels: refactorize

#2861 cambio parametro impresión
  resources/assets/js/components/loan/Ballots.vue
  resources/assets/js/components/loan/BallotsHipotecary.vue
  resources/assets/js/components/loan/Requirement.vue
  resources/assets/js/components/loan/Steps.vue
Labels: refactorize

#2862 Adicion de info del for solicitud
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/partials/footer.blade.php
Labels: refactorize

#2863 conversion de datos tipo string a float
  app/Loan.php
Labels: refactorize

#2864 observer
  app/Observers/MovementConceptObserver.php
Labels: refactorize

#2871 datos titular en historiales
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: enhancement

#2870 Boletas de pago y edición de los datos de la persona de referencia.
  resources/assets/js/components/workflow/BallotsAdjust.vue
  resources/assets/js/components/workflow/SpecificDataLoan.vue
Labels: enhancement

#2873 Dashboard. Agregando las columnas titular, ci y matricula
  resources/assets/js/components/dashboard/DataLoanInformation.vue
  resources/assets/js/components/dashboard/Index.vue
Labels: enhancement

#2875 Modificacion de contratos reunion 9/9/2021
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/long.blade.php
Labels: refactorize

#2877 Procedimiento almacenado para el saldo
  app/Loan.php
  database/migrations/2021_09_08_100507_create_function_total_payment_capital_loan.php
  database/migrations/2021_09_09_105537_create_function_balance_loan.php
Labels: enhancement, database

#2884 indice de endeudamiento
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: enhancement

#2885 Cambios en los contratos con confirmación para prod largo plazo
  resources/views/loan/contracts/long.blade.php
Labels: refactorize

#2893 Adicion de informacion de garante en la bandeja de amortizaciones
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#2894 visualizacion de informacion de prestamos del pvt inicio
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#2895 adicion de info para el append data list affiliate
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#2881 Modificacion de las restriccones de la tabla ajuste
  app/Http/Controllers/Api/V1/LoanContributionAdjustController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanContributionAdjustForm.php
  app/Http/Requests/LoanForm.php
  app/LoanContributionAdjust.php
  database/migrations/2021_03_04_091046_create_loan_contribution_adjusts_table.php
  database/migrations/2021_09_13_090213_add_database_name_to_loan_contribution_adjusts_table.php
  storage/responses/loan_contribution_adjust/store.200.json
Labels: refactorize

#2900 se quita indice de endeudamiento de garante en el formulario de calif…
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize
