Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2021-08, with the labels that each got.

#2732 reporte de amortizaciones COMANDO Y SENASIR con vistas y metodo de guardado de cobros fecha de transaccion
  app/Http/Controllers/Api/V1/ImportationReportController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#2734 primer y ultimo pago totales
  app/Loan.php
Labels: refactorize

#2736 dia endOfDay
  app/Loan.php
Labels: bug

#2735 cambio de encabezado amortizacion titular garante
  app/Http/Controllers/Api/V1/ImportationReportController.php
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
Labels: refactorize

#2737 bug
  app/Loan.php
Labels: bug

#2738 ajuste del reporte del listado de prestamos de comando
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2748 bug
  app/Loan.php
Labels: bug

#2749 bug
  app/Loan.php
  app/LoanPayment.php
Labels: bug

#2746 eliminacion de variables
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2753 ajuste pago
  app/Loan.php
Labels: bug

#2755 parametro reportes de mora
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: enhancement

#2754 validacion para no editar monto y plazo en caso do prestamos vigentes
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2756 campo loan_payment_date guardado de la hora en la importacion
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: refactorize

#2757 dias mora
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
Labels: bug

#2758 ordenar los prestamos senasir
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2760 filtraddo de solo estado pagado de reporte de amortizaciones
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: refactorize

#2764 ajuste en la validación del método validate_affiliate
  app/Http/Controllers/Api/V1/LoanController.php
Labels: validation

#2765 Adicion de Affiliate metodo verify loan_affiliates y formulario de so…
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#2766 se modifica de visulizacion de prestatarios que tengan a sus sposuse registrado
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#2770 bug mora
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: enhancement

#2771 cambio garante titular, mostrar observaciones, ocultar validación para archivo
  resources/assets/js/components/workflow/Add.vue
  resources/assets/js/components/workflow/AddObservation.vue
  resources/assets/js/components/workflow/ObserverFlow.vue
Labels: bug, refactorize

#2773 plan de pagos
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/LoanPlanPayment.php
  database/migrations/2021_08_13_093204_create_loan_payments_plan_table.php
  resources/views/loan/payments/payment_plan.blade.php
  routes/api.php
  storage/responses/loan/plan_payments.200.json
Labels: enhancement

#2775 Obtener observaciones segun el tipo en formulario de seguimiento
  resources/assets/js/components/tracing/Add.vue
  resources/assets/js/components/tracing/ObserverFlow.vue
Labels: bug

#2776 plan de pagos
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanPlanPayment.php
  database/migrations/2021_08_13_093204_create_loan_payments_plan_table.php
  routes/api.php
  storage/responses/loan/plan_payments.200.json
Labels: enhancement

#2777 creacion metodo para identificar esposa fallecida
  app/Spouse.php
Labels: enhancement

#2778 se agrega en detalle de esposa dead_spouse y ajuste del la validación de afiliados con esposas fallecidas
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement, refactorize

#2779 evaluacion categoria y verificacion de prestamo
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  routes/api.php
Labels: enhancement

#2781 Adición de alertas, observaciones
  resources/assets/js/components/affiliate/Dashboard.vue
  resources/assets/js/components/affiliate/Profile.vue
  resources/assets/js/components/payment/ListPaymentGenerate.vue
  resources/assets/js/components/payment/LoansGenerateList.vue
Labels: bug, enhancement

#2782 formulario de calificacion tamaño de letra
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2784 1ra version desembolsos de anticipo reporte
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  resources/views/loan/reports_tesoreria/output_report.blade.php
  storage/responses/loan/disbursement_receipt_form.200.json
Labels: enhancement

#2788 se agrega campos balance_previous_outputs y balance_later a la tabla …
  database/migrations/2021_06_16_162322_create_fund_rotatory_outputs_table.php
Labels: refactorize

#2790 quito return de desembolso
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#2783 Agregando visualización y loading.
  resources/assets/js/components/affiliate/Contributions.vue
  resources/assets/js/components/payment/ImportExportPayment.vue
  resources/assets/js/components/payment/Steps.vue
Labels: enhancement

#2792 parseo de fecha final report
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2795 se agrega campo amount_disbursed en la tabla fund_rotatory_outputs
  database/migrations/2021_06_15_083320_create_fund_rotatories_table.php
  database/migrations/2021_06_16_162322_create_fund_rotatory_outputs_table.php
Labels: refactorize

#2796 Guardado de las salidas del fondo rotatorio con nuevos campos
  app/FundRotatoryOutput.php
  app/Http/Requests/FundRotatoryForm.php
Labels: enhancement

#2797 Ruta para verificar fondo rotatorio desembolsos y cambio de nombre me…
  app/Http/Controllers/Api/V1/FundRotatoryController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  routes/api.php
  storage/responses/fund_rotary_entry/verify_fund_rotatory_disbursements.200.json
  storage/responses/loan/disbursement_receipt_form.200.json
Labels: enhancement

#2822 listado de movimientos de fondo rotattorio
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
  app/MovementFundRotatory.php
  routes/api.php
  storage/responses/movements/list_movements_fund_rotatory.200.json
Labels: enhancement

#2823 Metodo para cierre de gestión de la tabla mvimientos
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
  routes/api.php
  storage/responses/movements/closing_movements.200.json
Labels: enhancement

#2824 metodo de ingreso del fondo rotatorio
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
  app/Http/Requests/MovementFundRotatoryForm.php
  routes/api.php
  storage/responses/movements/store_input.200.json
Labels: enhancement

#2825 reporte de caja fondo rotario
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
  resources/views/loan/reports_tesoreria/cash_report.blade.php
  storage/responses/movements/cash_report.200.json
Labels: enhancement

#2827 visualizacion del saldo final del reporte de caja del fondo rotatorio
  resources/views/loan/reports_tesoreria/cash_report.blade.php
Labels: enhancement

#2829 se crea validacio de monto de ingreso y salida
  app/Http/Requests/MovementFundRotatoryForm.php
Labels: enhancement

#2830 MOd de catch
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
Labels: refactorize

#2831 cambio en la generacion de codigo en el ingreso del fondo rotatorio
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
Labels: enhancement

#2833 mod de mov fun rotatory
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
Labels: refactorize

#2835 Cierre cod
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
Labels: refactorize

#2836 Se agrega tipo de concepto a la descripcion en el reporte de caja
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
  resources/views/loan/reports_tesoreria/cash_report.blade.php
Labels: refactorize

#2837 MOdificacion del vocher de tesoreria
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/VoucherController.php
  app/Http/Requests/VoucherForm.php
  resources/views/loan/payments/payment_voucher.blade.php
Labels: refactorize

#2838 Creación de permiso para el registro de un nuevo fondo rotatorio
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
  routes/api.php
  storage/responses/movements/store_input.200.json
Labels: enhancement, refactorize

#2839 api adicion de permisos, borrads de rutas no usadas,y orden de reportes
  resources/views/loan/payments/payment_voucher.blade.php
  routes/api.php
Labels: refactorize

#2840 creacion de permisos para el fondo rotatorio
  database/seeds/LoanPermissionSeeder.php
Labels: enhancement, refactorize
