Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2021-05, with the labels that each got.

#1974 Agregar en el método update del loan, registro de fecha de desembolso con permiso
  app/Http/Controllers/Api/V1/LoanController.php
  database/seeds/LoanPermissionSeeder.php
Labels: enhancement

#1975 modificacion a etiquetado refinanciamiento
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#1977 kardex de pagos
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  storage/responses/loan_payment/indexKardex.200.json
Labels: enhancement

#1981 Crear método para obtener requisitos con su numero de orden y visualizar en el formulario de solicitud
  app/Loan.php
  resources/views/loan/forms/request_form.blade.php
Labels: enhancement, refactorize

#1978 primer pago
  app/Loan.php
  app/LoanPayment.php
Labels: bug

#1983 bug permiso fecha de desembolso disbursement-loan
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#1984 reporte excel del listado de prestamos
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#1986 añadir informacion del loan
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/loan/show.200.json
Labels: refactorize

#1987 bug de orden de requisitos en el formulario de solicitud
  app/Loan.php
Labels: bug

#1988 ultima cuota y redondeos
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Loan.php
  app/LoanPayment.php
Labels: enhancement

#1994 Desembolso en efectivo para adicionar firmas
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: enhancement

#2002 modalidad
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: enhancement

#2003 bug cambio de tipo de dato de entero a float
  app/Http/Requests/LoanForm.php
  database/migrations/2019_11_01_094319_create_loan_affiliates_table.php
Labels: bug

#2004 cancelacion de prestamo
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Loan.php
  app/Observers/LoanPaymentObserver.php
Labels: enhancement

#2006 generar formulario de calificación caso hipotecario con visualización de sus boletas titular y codeudor
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  resources/views/loan/forms/qualification_form.blade.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#2007 bug inpresion formulario de calificacion senasir
  resources/views/loan/forms/qualification_form.blade.php
Labels: bug

#2016 validacion de datos
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: bug

#2015 Envió de archivo excel en la importación con ci de pagos excedentes
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  storage/responses/loan/list_loans_generate.200.json
Labels: refactorize

#2018 eliminacion de ids
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Loan.php
Labels: refactorize

#2019 afiliateForm
  app/Affiliate.php
  app/Http/Requests/AffiliateForm.php
Labels: validation

#2020 Modificacion de seeders de permisos
  database/seeds/AdvanceRoleSeeder.php
Labels: database

#2021 Arreglo de obtencion de modalidad en caso cpop LP
  app/Loan.php
Labels: refactorize

#2025 eliminar código
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
Labels: bug, refactorize

#2024 Validadcion en el loanform
  app/Http/Requests/LoanForm.php
Labels: validation

#2026 Litado afiliados modificacion
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#2027 Se realizo el guardado de num_accounting_voucher
  resources/assets/js/components/loan/SpecificDataLoan.vue
Labels: enhancement

#2028 validacion
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
Labels: bug

#2029 Adicion de validacion de listado de prestamo
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2031 validacion primera cuota
  app/Loan.php
Labels: validation

#2032 diferencia de dias primera cuota
  app/Loan.php
Labels: validation

#2034 Bug loan
  app/Loan.php
Labels: bug

#2035 bug
  app/Loan.php
Labels: bug

#2036 bug formulario de cobro
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#2038 kardex
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Loan.php
Labels: enhancement

#2039 se realizo el cambio de nombre en garantes cuando es rehacer
  resources/assets/js/components/loan/Guarantor.vue
Labels: bug

#2044 bugs y adicion de permisos
  database/seeds/AdvanceRoleSeeder.php
  resources/views/loan/contracts/long.blade.php
Labels: bug

#2045 Cambio de valdaciones de garantes
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: validation

#2046 se arreglo el error de quota_treat
  resources/assets/js/components/loan/BallotsResultHipotecary.vue
Labels: bug

#2047 Envio de second name en lista generate
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2049 redondeo en pagos
  app/Helpers/Util.php
  app/Loan.php
  app/LoanPayment.php
Labels: refactorize

#2065 Se cambio el nombre de la descripción en la amortización para los pendientes por confirmar
  resources/assets/js/components/payment/AddAmortization.vue
Labels: bug

#2067 tag amortizando y mora
  app/Console/Kernel.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: enhancement

#2069 Correccion de la exportacion e importacion de pagos
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  config/translations.php
Labels: refactorize

#2070 bug contrato refinanciamiento
  resources/views/loan/contracts/long.blade.php
Labels: bug

#2072 Listado de pagos con filtros
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  routes/api.php
  storage/responses/loan_payment/list_loan_payment_generate.200.json
Labels: enhancement

#2077 cambio de fecha a fecha y hora
  resources/views/loan/payments/payment_kardex.blade.php
Labels: bug

#2081 Cambio de sub modalidades estados a cobranzas
  app/AmortizationType.php
  app/Http/Controllers/Api/V1/AmortizationTypeController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Requests/LoanPaymentForm.php
  app/LoanPayment.php
  app/LoanPaymentState.php
  app/LoanState.php
  database/migrations/2019_10_31_084035_create_loans_table.php
  database/migrations/2019_11_04_093204_create_loan_payments_table.php
  database/migrations/2021_05_09_211940_create_loan_payment_states_table.php
  database/seeds/AmortizationTypeSeeder.php
  database/seeds/LoanPaymentStateSeeder.php
  database/seeds/LoanStateSeeder.php
  database/seeds/ProcedureAmortizationSeeder.php
  database/seeds/VoucherTypeSeeder.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
  routes/api.php
  storage/responses/loan/set_payment.200.json
  storage/responses/loan_payment/bulk_destroy.200.json
  storage/responses/loan_payment/bullk_update_role.200.json
  storage/responses/loan_payment/destroy.200.json
  storage/responses/loan_payment/importation_payments.200.json
  storage/responses/loan_payment/importation_pending.200.json
  storage/responses/loan_payment/index.200.json
  storage/responses/loan_payment/indexKardex.200.json
  storage/responses/loan_payment/list_loan_payment_generate.200.json
  storage/responses/loan_payment/show.200.json
  storage/responses/loan_payment/update.200.json
  storage/responses/voucher/delete_voucher_payment.200.json
  version-seeder.sh
Labels: database, duplicate, enhancement, refactorize

#2082 Correccion de los estados
  app/Http/Controllers/Api/V1/VoucherController.php
  app/Loan.php
  app/LoanPayment.php
Labels: refactorize

#2083 Correccion de estados y verificacion de cambio de metodos de cobros
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#2084 datos del ultimo pago validado
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug, refactorize

#2085 Modificacion de cambio de estados y arreglo del voucher
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/VoucherController.php
  app/Http/Requests/VoucherForm.php
  app/Spouse.php
  app/Voucher.php
  database/factories/LoanFactory.php
  database/migrations/2020_07_21_094005_add_data_to_vouchers.php
  database/seeds/LoanStateSeeder.php
Labels: database, refactorize

#2086 modificaciones al voucher en base y codigo
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Requests/VoucherForm.php
  app/Voucher.php
  database/migrations/2020_07_21_094005_add_data_to_vouchers.php
Labels: database, refactorize

#2087 se agrega jefatura al flujo de prestamo
  database/seeds/RoleSequenceSeeder.php
Labels: refactorize

#2090 next payment y payment states
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanPaymentForm.php
  app/Loan.php
  app/LoanPayment.php
  database/migrations/2019_11_04_093204_create_loan_payments_table.php
Labels: enhancement

#2091 modificacion de la fecha de la migracion
  database/migrations/2019_01_04_211940_create_loan_payment_states_table.php
Labels: database

#2093 modificacion de loanpayment y kardex
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/LoanPayment.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: refactorize

#2095 descuentos garantias y monto subsistencia
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: enhancement

#2098 Modificación del recibo del voucher
  app/Http/Controllers/Api/V1/VoucherController.php
  resources/views/loan/payments/payment_voucher.blade.php
Labels: refactorize

#2105 cambiando categoria de afiliados por respuesta de ruta del listado
  resources/assets/js/components/affiliate/List.vue
  resources/assets/js/components/payment/ListPaymentGenerate.vue
Labels: bug, refactorize

#2107 Voucher confirmacion
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: validation

#2119 modificacion del metodo importation_command_senasir para la importacion
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#2117 LISTA DE GENERACION DE REPORTES DE PAGOS
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/contracts/advance.blade.php
  storage/responses/loan_payment/list_loan_payment_generate.200.json
  storage/responses/loan_payment/show.200.json
Labels: refactorize

#2120 commit
  resources/assets/js/components/payment/ImportExport.vue
Labels: refactorize

#2122 Adicinar campos a listado de pagos
  resources/assets/js/components/payment/ListPaymentGenerate.vue
Labels: enhancement, refactorize

#2123 bug cobro
  app/Loan.php
Labels: bug

#2124 Se agrego el campo de fecha a el loan payment juanto a permisos y mo…
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Requests/LoanPaymentForm.php
  app/LoanPayment.php
  database/migrations/2019_11_04_093204_create_loan_payments_table.php
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: database, refactorize

#2127 se modifica texto de formulario de calificacion
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#2125 cambio de modalidad nombre de aomortiz
  database/seeds/ProcedureAmortizationSeeder.php
Labels: refactorize

#2130 Generar excel para descargar registro de pagos
  resources/assets/js/components/dashboard/ChangeRol.vue
  resources/assets/js/components/payment/ImportExport.vue
  resources/assets/js/components/payment/ListLoanGenerate.vue
  resources/assets/js/components/payment/ListPaymentGenerate.vue
Labels: enhancement

#2131 excel exportacion y pagos por periodo
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  routes/api.php
Labels: enhancement, refactorize

#2132 bug edicion de pago
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/UserController.php
  database/seeds/ProcedureAmortizationSeeder.php
  storage/responses/loan_payment/list_loan_payment_generate.200.json
Labels: bug

#2134 Crear interfaz de cambio de rol para le usuario y métodos
  resources/assets/js/components/dashboard/ChangeRol.vue
  resources/assets/js/layout/App.vue
  resources/assets/js/layout/Appbar.vue
  resources/assets/js/layout/Navbar.vue
Labels: enhancement

#2133 se modifico la validacion de refinanciamiento y se arreglo el editado…
  resources/assets/js/components/loan/Steps.vue
  resources/assets/js/components/payment/Steps.vue
Labels: bug

#2136 bug importacion metodo senasir
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#2140 Generacion de pagos automaticos y excel
  app/Exports/FileWithMultipleSheets.php
  app/Exports/MultipleSheetsExport.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  storage/responses/loan_payment/payments_per_period.200.json
Labels: enhancement

#2142 adicion del numero de cuenta en el el form solicitud para cierre de ticket
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2143 Adicion de informacion del domicilio en el form de solicitud
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2144 Correccion bug de contrato largo plazo
  resources/views/loan/contracts/long.blade.php
Labels: refactorize

#2160 metodo historial de pagos de un prestamo
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  routes/api.php
  storage/responses/loan_payment/payment_history.200.json
Labels: enhancement

#2162 Listado de cobros tesoreria
  app/Http/Controllers/Api/V1/VoucherController.php
  app/Voucher.php
  storage/responses/voucher/index.200.json
Labels: refactorize

#2167 método para eliminar el ultimo registro de la tabla loan_payment
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  routes/api.php
  storage/responses/loan_payment/delete_last_record_payment.200.json
Labels: enhancement

#2168 bug ,modificacion en api ruta metodo de eliminacon de ultimo registro
  routes/api.php
Labels: bug

#2169 validar la eliminacion de registro de cobro en amortizacion directa n…
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  database/seeds/LoanPermissionSeeder.php
Labels: refactorize

#2170 formato fechas y solucion records
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: enhancement

#2172 ajuste del método de eliminación vaucher en estado pagado con permiso delete-voucher-paid
  app/Http/Controllers/Api/V1/VoucherController.php
Labels: refactorize

#2171 primera cuota
  app/Loan.php
  app/LoanInterest.php
  app/LoanPayment.php
Labels: bug

#2173 Reportes de amortizaciones y prestamos cantidad 6
  app/Exports/MultipleSheetExportPayment.php
  app/Exports/SheetExportPayment.php
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  routes/api.php
  storage/responses/report_loans/loan_desembolsado.200.json
  storage/responses/reports_amortizations/dincuent_cash_deposit.200.json
  storage/responses/reports_amortizations/dincuent_months_t_g.200.json
  storage/responses/reports_amortizations/report_amortization_ajust.200.json
  storage/responses/reports_amortizations/report_amortization_pending.200.json
  storage/responses/reports_amortizations/report_complement_fondo.200.json
Labels: enhancement

#2175 Reporte de estado de cartera Vigente y desembolsado
  app/Http/Controllers/Api/V1/LoanReportController.php
  routes/api.php
Labels: enhancement

#2176 cambio de forma del formulario de de cobros
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#2178 Reportes de prestamos en mora
  app/Exports/MultipleSheetExportPaymentMora.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
  routes/api.php
Labels: refactorize

#2189 incluir registros eliminados al historico
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#2191 reportes amortizaciones garantes
  app/Exports/FileWithMultipleSheetsDefaulted.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  routes/api.php
Labels: enhancement

#2192 Creación de permisos para listado de comprobantes y ver reportes de cobranzas
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
Labels: bug, enhancement

#2194 correccion de fecha del plan de pagos, y adicion de permiso a cobranzas
  database/seeds/AdvanceRoleSeeder.php
  resources/views/loan/payments/payment_kardex.blade.php
Labels: bug, refactorize

#2195 bug imprecion
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#2198 cronjob amortizacion garantes
  app/Console/Kernel.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanInterest.php
  app/LoanPayment.php
  app/Observers/LoanObserver.php
Labels: enhancement

#2196 se adiciono el permiso para la edicion de documentos
  resources/assets/js/components/workflow/DocumentsFlow.vue
Labels: bug

#2199 formato fechas
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#2201 visualizacion de loa formulario de cobro eliminado
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#2207 cambio de estado de un prestamo de liquidado a vigente en caso de anulación de pago
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#2208 adición de liquidate al guardar amortizacion
  resources/assets/js/components/payment/Steps.vue
Labels: bug

#2211 redondeos
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
Labels: refactorize

#2214 listado de prestamos vigentes
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2217 Cambio de formato del formulario de Cobros
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#2220 se agrega un a los miles
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#2221 bug visualizacion de monto de ajuste en formulario de calificacion
  app/Loan.php
Labels: refactorize

#2223 cambio de formato fecha desembolso
  resources/assets/js/components/payment/AddAmortization.vue
Labels: bug

#2224 cambio de texto formulario de cobro pagado por
  resources/views/loan/payments/payment_loan.blade.php
Labels: bug

#2219 modificacion del form de calificacion formatos
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#2225 cambio automatico cobros garantes
  app/Console/Kernel.php
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Observers/LoanObserver.php
Labels: enhancement

#2228 plan de pagos
  app/Loan.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: enhancement

#2227 corrección de texto
  resources/views/loan/payments/payment_loan.blade.php
Labels: bug

#2231 Reporte de mora correccion
  app/Exports/MultipleSheetExportPaymentMora.php
  app/Exports/SheetExportPayment.php
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: bug

#2237 quitar a garantes del reporte de cartera
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2242 Cambio de extencion a xls de xlsx
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  database/seeds/LoanGlobalParameterSeeder.php
Labels: refactorize

#2244 redondeo
  app/Helpers/Util.php
Labels: bug

#2245 cambio de parametro global para el borrado de pagos
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  database/seeds/LoanGlobalParameterSeeder.php
Labels: refactorize

#2249 VAlidadcion de modalidades repetidas
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
Labels: refactorize

#2252 formato de de hora plan de pagos y kardex
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#2254 correccion punto de mil y coma de desimal
  resources/views/loan/forms/request_form.blade.php
Labels: refactorize

#2256 estados de los prestamos
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Observers/LoanPaymentObserver.php
Labels: bug

#2257 decimales en contratos
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/reprogramming.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: bug

#2260 Cambio de extencion
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#2261 primera cuota exportacion
  app/Loan.php
  app/LoanPayment.php
Labels: bug

#2262 desimales y fecha en reportes de prestamos
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: bug, refactorize

#2264 datos adicionales en kardex
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: enhancement

#2266 REportes de amortizaciones formateo de fechas y numeros
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: refactorize

#2267 bug kardex
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: bug

#2271 reporte de cartera adicion de parametros
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
Labels: refactorize

#2274 Bug reporte mora
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: bug

#2275 adicion de datos en el reporte de amortizaciones efec y dep cuenta
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
Labels: refactorize

#2281 crear meto de validación para la edición de un préstamo y ajuste del método de edilicio
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: bug

#2282 excel pagos automaticos
  app/Exports/FileWithMultipleSheets.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#2284 bug metodo de validacion
  app/Loan.php
Labels: bug

#2283 Modificacion de contrato de anticipo quitar negrillas
  resources/views/loan/contracts/advance.blade.php
Labels: refactorize

#2285 formulario de calificacion
  resources/views/loan/forms/qualification_form.blade.php
Labels: bug

#2286 Se aumenta el formateo de un mil en literal para contratos
  app/Helpers/Util.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#2287 se puso requerido el primer campo de telefono
  resources/assets/js/components/affiliate/PersonalInformation.vue
  resources/assets/js/components/loan/Steps.vue
Labels: bug

#2288 se agrega campo código de transaccional al historial de cobros
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize
