Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2021-02, with the labels that each got.

#1421 correccion de plan de pagos y calculo 360 dias
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/LoanPayment.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: enhancement

#1422 modificacion de las migracion records
  database/migrations/2019_09_23_161220_create_records_table.php
  database/migrations/2021_02_09_134206_add_role_to_records.php
Labels: database, enhancement

#1425 bandeja de cobros
  app/Helpers/Util.php
  app/Http/Requests/LoanPaymentForm.php
  database/migrations/2019_11_04_093204_create_loan_payments_table.php
Labels: enhancement

#1435 Estaditsico y filtrado de plan de pagos
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/StatisticController.php
  app/LoanPayment.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: enhancement

#1433 libreria QR y adicion de informacion en el pie de pagina en los contratos
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/VoucherController.php
  composer.json
  config/app.php
  resources/views/partials/footer.blade.php
Labels: dependencies, enhancement

#1440 modificación de la impresion del kardex cliente
  resources/views/loan/payments/payment_kardex.blade.php
Labels: refactorize

#1437 Adicionar informacion plan de pagos con codeudores y modificacion de next payment para el calculo del cobro
  app/Loan.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: refactorize

#1442 Eliminacion en lote de pagos
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  routes/api.php
  storage/responses/loan_payment/bulk_destroy.200.json
Labels: enhancement

#1443 Correccion de calculos next payment
  app/Http/Controllers/Api/V1/StatisticController.php
  app/Loan.php
  app/LoanPayment.php
Labels: refactorize

#1450 Correccion LoanPaymet relacion User
  app/LoanPayment.php
Labels: bug

#1451 estadistico cobros
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/StatisticController.php
  app/LoanPayment.php
Labels: bug

#1452 adicion de usuario al guardar nuevo registro de pago
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/loan/set_payment.200.json
Labels: refactorize

#1456 Derivacion e imprecion de comprobante de derivacion a otras areas
  app/Events/LoanPaymentFlowEvent.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/flow/tbody/loan_payment.blade.php
  resources/views/flow/thead/loan_payment.blade.php
  storage/responses/loan_payment/bullk_update_role.200.json
Labels: enhancement, refactorize

#1457 modificacion de metodos index y registr payment(exportacion)
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/LoanPayment.php
Labels: refactorize

#1459 Modificacion del metodo set_voucher adicion de usuario - flujos
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#1462 Ajuste set_payment usuario si se envia o no el usuario
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize
