Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2021-04, with the labels that each got.

#1657 Ajuste al metodo de obtencion de contribuciones
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#1663 creación del campo sequence_number_flow para el flujo de prestamos en…
  app/Http/Controllers/Api/V1/ProcedureTypeController.php
  app/Http/Requests/RoleSequenceForm.php
  database/migrations/2020_03_19_084610_create_role_sequences_table.php
Labels: enhancement

#1665 Modificación de los métodos de flujos de trabajo para las diferentes
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/ModuleController.php
  app/Module.php
  app/RoleSequence.php
Labels: refactorize

#1668 sincronizacion de usuarios
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/UserController.php
  app/Http/Requests/UserForm.php
  routes/api.php
Labels: enhancement

#1669 Reprogramacion modificaciones de como procedure
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  database/migrations/2019_10_31_084035_create_loans_table.php
  database/seeds/LoanStructureSeeder.php
Labels: database, enhancement, refactorize

#1671 modificacion de validacion
  app/Http/Requests/LoanForm.php
Labels: validation

#1672 Sedder destinos de prestamos refinanciandos y cor ortog
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  database/seeds/LoanDestinyProcedureTypeSeeder.php
  database/seeds/LoanStructureSeeder.php
  resources/assets/js/components/loan/Ballots.vue
  resources/assets/js/components/loan/Steps.vue
Labels: database

#1675 Aumento de columnas a la tabla de paremeterss loan, y loan estructure…
  app/LoanModalityParameter.php
  database/migrations/2019_11_29_112944_create_loan_modality_parameters_table.php
  database/seeds/LoanStructureSeeder.php
  storage/responses/affiliate/affiliate_evaluate_loans.200.json
  storage/responses/affiliate/get_loan_modality.200.json
  storage/responses/procedure_modality/get_loan_modality_parameter.200.json
Labels: enhancement, refactorize

#1676 validacion para hipotecario de afiliado con item 0
  app/Loan.php
Labels: refactorize

#1678 cargar en el seeder flujo de trabajo con el nueva secuencia creada sequence_number_flow
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/RoleSequenceSeeder.php
Labels: refactorize

#1686 Método para verificar si el afiliado tiene contribuciones y enviar los tags al detalle del préstamo
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/loan/show.200.json
Labels: enhancement

#1689 Validación de flujo de trabajo
  app/Http/Controllers/Api/V1/ProcedureTypeController.php
  database/seeds/RoleSequenceSeeder.php
Labels: validation

#1691 Recuperar datos del padre y devolver el second name
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/loan/show.200.json
Labels: refactorize

#1694 Agregar en la obtencion de modalidad si es cpop
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
Labels: refactorize

#1696 validacion para que usuario comision no pueda ser garante
  app/Affiliate.php
  app/Http/Controllers/Api/V1/ProcedureTypeController.php
Labels: refactorize

#1699 Llamar al parent loan en el detalle del prestamo
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#1700 Adicion de datos del parent loan en el detalle
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/loan/show.200.json
Labels: refactorize

#1701 correccion de bug el detalle del prestamo
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#1697 generacion de pagos automaticos
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Loan.php
  app/LoanPayment.php
Labels: enhancement

#1707 Validar en print_loan_payment no sume saldo anterior cobros anulados
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#1708 quitar modalidad de cpop sector pasivos
  app/Loan.php
Labels: refactorize

#1711 pagos modalidad
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanPaymentForm.php
  app/Loan.php
  app/LoanPayment.php
  storage/responses/loan/get_next_payment.200.json
Labels: enhancement

#1714 amortizaciones
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Requests/LoanPaymentForm.php
  app/Loan.php
  app/LoanPayment.php
Labels: refactorize

#1719 Agregar usuario al importar pagos
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#1720 Adcion de casos para cobros sub
  app/Loan.php
Labels: refactorize

#1723 Correccion de devolucion de procedures, rspuesta demorada
  app/Helpers/Util.php
Labels: bug, refactorize

#1722 Se realizo el cambio de validación de roles a permisos
  resources/assets/js/components/payment/Add.vue
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/payment/Steps.vue
Labels: bug

#1724 arreglo contador de amortizaciones
  app/Helpers/Util.php
Labels: refactorize

#1727 kardex pagos
  app/Loan.php
  resources/views/loan/payments/payment_kardex.blade.php
Labels: enhancement

#1730 Se realizo la edición de pago cuando es amortización por fondo y comp…
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/payment/Steps.vue
Labels: bug

#1731 amortizacion cambiar a pagabdo ala actualizar
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#1733 arreglo de edicion de pago cobranzas
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: enhancement, refactorize

#1735 Método para obtener el filtrado del historial de cobro
  app/Http/Controllers/Api/V1/RecordController.php
  routes/api.php
  storage/responses/record/get_record_loan_payment.200.json
Labels: enhancement

#1738 LoanPayment añadir mas info al detalle y adicon de documentacion
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  storage/responses/loan_payment/show.200.json
Labels: refactorize

#1740 Crear Método para anular vaucher y registro de cobro
  app/Http/Controllers/Api/V1/VoucherController.php
  routes/api.php
  storage/responses/voucher/delete_voucher_payment.200.json
Labels: enhancement

#1746 validacion Refinanciamiento Préstamo hipotecario
  app/Http/Requests/LoanForm.php
Labels: bug

#1750 se adiciona estado al método indexKardex
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#1751 ajuste detalle del estado de un estado de pago
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#1756 pendientes de ajuste
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: enhancement

#1757 Ajuste de eliminar pagos en estado pendiente y actualizar estado
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: refactorize

#1758 ajuste de print_loan_payment para imprimir formulario
  app/Http/Controllers/Api/V1/LoanPaymentController.php
Labels: bug

#1764 Quitar la validación de requerido la ciudad de expedición del carnet
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/AffiliateForm.php
Labels: refactorize

#1768 ajuste de validación del ente gestor
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#1769 Adicionar informacion del prestamo para mostrar datos a cobranzas
  app/Http/Controllers/Api/V1/LoanController.php
  config/translations.php
  storage/responses/loan/show.200.json
Labels: refactorize

#1770 columnas kardex
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/payments/payment_kardex.blade.php
Labels: enhancement

#1771 Seeder de submodalidades de amortizaciones y cambio de estado
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Loan.php
  database/seeds/LoanStateSeeder.php
  database/seeds/ProcedureAmortizationSeeder.php
  storage/responses/loan_payment/show.200.json
Labels: database, refactorize

#1772 Arreglo seeder hipotecario cpop
  database/seeds/LoanStructureSeeder.php
Labels: database

#1773 Quitar validadcion del registro de la direccion
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize, validation

#1776 ajuste del metodo test_guarantor, creacion del metodo verify_double_p…
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: bug, enhancement, refactorize

#1777 Arreglo bug Affiliate
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: bug

#1781 ajuste del método test_guarantor para la cónyuge
  app/Http/Controllers/Api/V1/AffiliateController.php
  storage/responses/affiliate/test_guarantor.200.json
Labels: refactorize

#1782 Bug de obtencion de modalidad del largo plazo sector pasivo
  app/Loan.php
Labels: bug

#1783 prestamos como esposa
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Spouse.php
  storage/responses/affiliate/affiliate_history.200.json
Labels: enhancement

#1788 Agregar datos de evaluación del garante en formulario de Calificación
  resources/views/loan/forms/qualification_form.blade.php
Labels: enhancement

#1793 Amortización por prioridades en la importación Caso garantes y titulares
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/LoanPayment.php
Labels: enhancement

#1798 datos extras del afiliado
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  storage/responses/affiliate/affiliate_record.200.json
Labels: enhancement

#1801 Se agrego informacion para el listado del affiliado
  app/Http/Controllers/Api/V1/AffiliateController.php
  storage/responses/affiliate/index.200.json
Labels: refactorize

#1803 Modificar print_loan_payment.php y payment_loan.blade para agregar viudas como garante
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#1806 prestamos vigentes del afiliado
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: enhancement

#1807 bug verify_guarantor
  app/Affiliate.php
Labels: bug

#1805 Se delimito para que un afiliado en estado de disponibilidad no accede a refis
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#1810 saldos de prestamos
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Spouse.php
  resources/views/loan/forms/request_form.blade.php
Labels: enhancement

#1814 historico
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Spouse.php
  routes/api.php
Labels: bug

#1816 kardex viudas
  app/Observers/LoanPaymentObserver.php
  resources/views/loan/payments/payment_kardex.blade.php
Labels: bug

#1817 se agrega contabilidad y presupuesto en los seeders de permisos y flujo de trabajo
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
  database/seeds/RoleSequenceSeeder.php
Labels: enhancement

#1818 Adicion de campos para el loan y cambio de modalidad de disponibilidad
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/AffiliateForm.php
  app/Http/Requests/LoanForm.php
  app/Loan.php
  database/migrations/2019_10_31_084035_create_loans_table.php
  database/migrations/2021_04_20_163751_add_description_unit_to_affiliates.php
  database/seeds/LoanStructureSeeder.php
  resources/views/loan/contracts/short.blade.php
  storage/responses/affiliate/affiliate_evaluate_loans.200.json
Labels: database, refactorize

#1846 Crear método para obtener roles y permisos
  app/Http/Controllers/Api/V1/UserController.php
  routes/api.php
  storage/responses/user/get_roles_permission.200.json
Labels: enhancement

#1851 actualizar documento detalle de prestamo
  storage/responses/affiliate/show.200.json
Labels: refactorize

#1850 evaluacion de garantes
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  storage/responses/affiliate/test_guarantor.200.json
Labels: enhancement

#1854 adicion de parametros de intervalos por modalidad BD
  app/LoanModalityParameter.php
  database/migrations/2019_11_29_112944_create_loan_modality_parameters_table.php
  database/seeds/LoanStructureSeeder.php
Labels: database

#1855 Modificacion del metodo de la calculadora nuevos intervalos
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Rules/LoanIntervalAmount.php
  app/Rules/LoanIntervalTerm.php
  storage/responses/affiliate/get_loan_modality.200.json
Labels: refactorize

#1857 Modificacion del metodo para pre evaluacion
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/CalculatorController.php
  storage/responses/affiliate/affiliate_evaluate_loans.200.json
Labels: refactorize

#1859 método para editar monto y plazo del préstamo
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
  storage/responses/loan/edit_amounts_loan_term.200.json
Labels: enhancement

#1858 adición de permiso y vinculo para el área de legal para registro de fechas de contratos
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_plan.blade.php
  routes/api.php
  storage/responses/affiliate/get_loans.200.json
  storage/responses/loan/show.200.json
  storage/responses/loan/update.200.json
  storage/responses/loan_payment/importation_pending.200.json
  storage/responses/loan_payment/indexKardex.200.json
Labels: enhancement

#1860 Adicion de permisos para calificacion y recepcion
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
Labels: refactorize

#1866 kardex desplegado
  app/Affiliate.php
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Spouse.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: enhancement

#1874 Kardex
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
Labels: bug

#1876 calculo de pago
  app/Http/Requests/LoanPaymentForm.php
  app/LoanPayment.php
Labels: refactorize

#1861 adicion de permiso de aprobacion calificacion
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanStructureSeeder.php
Labels: database

#1877 cambio de tipo de dato
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  database/migrations/2019_11_29_112944_create_loan_modality_parameters_table.php
  database/seeds/AmortizationTypeSeeder.php
  database/seeds/PaymentTypeSeeder.php
Labels: database

#1878 creacion de controlador de contribuciones y relacion con el despiegue
  app/Breakdown.php
  app/Contribution.php
  app/Http/Controllers/Api/V1/ContributionController.php
  routes/api.php
  storage/responses/contributions/contributions.200.json
  storage/responses/contributions/contributions_affiliates.200.json
Labels: database, refactorize

#1879 ajuste del metodo edit_amounts_loan_term
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
Labels: refactorize

#1883 adicion de ruta para actualizar sismu
  app/Affiliate.php
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
  storage/responses/loan/update_sismu.200.json
Labels: enhancement, refactorize

#1886 modificacion del metodo para la edicion de monto y plazo
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#1888 calculo
  app/Loan.php
  app/Observers/LoanPaymentObserver.php
Labels: bug

#1884 Quitar del seeder contabilidad
  app/Http/Controllers/Api/V1/CalculatorController.php
  database/seeds/PaymentTypeSeeder.php
Labels: database

#1890 Creación del campo saldo de refinanciamiento
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  database/migrations/2019_10_31_084035_create_loans_table.php
Labels: enhancement

#1892 creación del permiso actualizar saldo de refinanciamiento en el seeder
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
Labels: enhancement

#1901 creación del Seeder ObservationTypeSeeder.php para observaciones del tramite
  database/seeds/ObservationTypeSeeder.php
  version-seeder.sh
Labels: enhancement

#1906 agregar validacion en la edicion de monto y plazo deacuerdo al proce…
  app/Http/Controllers/Api/V1/LoanController.php
Labels: validation

#1908 crear permiso para imprimir formulario de calificación y asignar permiso a calificación
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
Labels: enhancement

#1905 Refinanciamineto funcionalidad y fecha de corte de refinancimineto
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
  app/Loan.php
  app/LoanModalityParameter.php
  app/Sismu.php
  config/translations.php
  database/migrations/2019_11_29_112944_create_loan_modality_parameters_table.php
  database/migrations/2020_10_23_083301_create_sismu_table.php
  database/seeds/LoanStructureSeeder.php
  routes/api.php
  storage/responses/loan/show.200.json
  storage/responses/loan/update_refinancing_balance.200.json
  storage/responses/loan/update_sismu.200.json
Labels: database, documentation, enhancement, refactorize, validation

#1914 Contratos de anticipo y corto plazo generación en la creacion de tramite
  app/Http/Controllers/Api/V1/LoanController.php
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
  storage/responses/loan/show.200.json
Labels: refactorize

#1921 validacion
  app/Http/Controllers/Api/V1/AffiliateController.php
  resources/views/loan/forms/request_form.blade.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: enhancement

#1922 Modificacion de contratos para refinanciamiento
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#1924 bug
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: bug

#1931 modificación de datos de refinanciamiento en el formulario de calificación
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#1933 montos descontados
  app/Http/Controllers/Api/V1/CalculatorController.php
  storage/responses/calculator/store.200.json
Labels: enhancement

#1930 Adicion de permisos para editar personal de referencia y codeudor
  app/Http/Controllers/Api/V1/LoanController.php
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanPermissionSeeder.php
Labels: refactorize

#1934 validaciones garantes
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: validation

#1936 bug formulario de calificacion
  resources/views/loan/forms/qualification_form.blade.php
Labels: bug

#1941 Creacion de observadores del sismu
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Observers/SismuObserver.php
  app/Providers/AppServiceProvider.php
  app/Providers/SismuServiceProvider.php
  app/Record.php
  app/Sismu.php
  config/app.php
  database/seeds/AdvanceRoleSeeder.php
  storage/responses/module/get_modality_types.200.json
Labels: enhancement, refactorize

#1942 colocar etiquetas de refi y repro solo a pos pvt
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#1944 creación del campo valor comercial valor rescate en loan_property
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPropertyController.php
  app/Http/Requests/LoanForm.php
  app/Loan.php
  app/LoanPayment.php
  app/LoanProperty.php
  database/migrations/2019_10_31_084033_create_loan_properties_table.php
  database/migrations/2019_10_31_084035_create_loans_table.php
  database/migrations/2019_11_01_094319_create_loan_affiliates_table.php
  database/migrations/2019_11_04_093204_create_loan_payments_table.php
  storage/responses/loan/index.200.json
  storage/responses/loan/show.200.json
  storage/responses/loan/store.200.json
  storage/responses/loan_property/index.200.json
  storage/responses/loan_property/show.200.json
  storage/responses/loan_property/store.200.json
Labels: enhancement

#1945 Quitar taloansbla de intervalos y adicion de campo datetime en
  app/Http/Controllers/Api/V1/LoanIntervalController.php
  app/LoanInterval.php
  app/ProcedureType.php
  database/migrations/2019_10_31_084035_create_loans_table.php
  database/migrations/2019_11_19_151555_create_loan_intervals_table.php
  routes/api.php
Labels: database, refactorize

#1947 Cambio de nombre de procedure_type y procedure_modalities en los seeders
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanDestinyProcedureTypeSeeder.php
  database/seeds/LoanStructureSeeder.php
  database/seeds/RoleSequenceSeeder.php
Labels: refactorize

#1948 Listado de prestamos generación primera parte
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
  storage/responses/loan/list_loans_generate.200.json
Labels: enhancement

#1949 validacion
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: validation

#1953 modalidades pestamos cambios
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  database/seeds/LoanPermissionSeeder.php
Labels: refactorize

#1956 Realizar modificación de procediure_modalities en contratos
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#1958 registro de estatus activo del afiliado y registro de la quota fija loan y correcion de bug
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: refactorize

#1957 modificacion de contrato largo plazo
  resources/views/loan/contracts/long.blade.php
Labels: refactorize

#1961 Modificación y añadido de permisos, agregar quota al metodo list generate
  app/Http/Controllers/Api/V1/LoanController.php
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/LoanStructureSeeder.php
  database/seeds/ProcedureAmortizationSeeder.php
  routes/api.php
Labels: database, refactorize

#1965 modificar saldo del formulario de cobros
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#1967 Quitar validacion
  app/Http/Requests/LoanPaymentForm.php
Labels: refactorize

#1968 Composer lock
  composer.lock
Labels: refactorize
