Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2021-03, with the labels that each got.

#1469 Adicion metodo contribuciones adicionando logica para loa pasivos
  app/AidContribution.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  storage/responses/affiliate/get_contributions.200.json
Labels: refactorize

#1472 modificacion next payment
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/LoanPayment.php
  database/migrations/2019_11_04_093204_create_loan_payments_table.php
Labels: enhancement

#1475 modificacion
  app/Loan.php
  app/LoanPayment.php
Labels: bug

#1476 comprobante de pago
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: enhancement

#1477 Adicion de informacion de registro de cobro en el comprobante de derivacion
  resources/views/flow/bulk_flow_procedures.blade.php
  resources/views/flow/tbody/loan_payment.blade.php
  resources/views/flow/thead/loan_payment.blade.php
Labels: refactorize

#1479 pago manual y kardex
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanPayment.php
  resources/views/loan/payments/payment_kardex.blade.php
Labels: enhancement

#1484 contribuciones pasivos activos e item 0
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: enhancement, refactorize

#1488 creación del método de validación para garante verify_guarantor
  app/Affiliate.php
Labels: enhancement

#1489 Contribution adicion para Datos para item 0
  app/Http/Controllers/Api/V1/AffiliateController.php
  storage/responses/affiliate/get_contributions.200.json
Labels: refactorize

#1491 actualizacion plan de pagos
  app/Loan.php
  app/LoanPayment.php
Labels: bug

#1492 creación del campo para numero de comprobante contable y numero de ce…
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
  app/Loan.php
  database/migrations/2019_10_31_084035_create_loans_table.php
  storage/responses/loan/update.200.json
Labels: database, refactorize, validation

#1494 Adicion de campos para la relacionde contribuciones con el prestamo
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
  app/Loan.php
  database/migrations/2019_11_01_094319_create_loan_affiliates_table.php
  storage/responses/loan/store.200.json
Labels: enhancement, refactorize, validation

#1496 Adicion de datos en el metodo contribution
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/affiliate/get_contributions.200.json
Labels: refactorize

#1500 Modificacion del metodo de contribuciones
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
Labels: bug

#1502 bug primer pago
  app/Loan.php
  app/LoanPayment.php
Labels: bug

#1503 dias de alivio
  database/migrations/2019_11_06_094202_create_loan_global_parameters_table.php
  database/seeds/LoanGlobalParameterSeeder.php
Labels: enhancement

#1504 arreglo de validacion boolean en contributions
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: bug

#1505 Correccion ortografico
  routes/api.php
  storage/responses/aid_contribution/index.200.json
Labels: bug

#1506 dias de alivio
  app/Loan.php
Labels: enhancement

#1508 correccion de Calculos del liquido para calificacion
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug, refactorize

#1512 Metodos para rehacer el prestamo
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
  app/Observers/LoanObserver.php
  storage/responses/calculator/store.200.json
Labels: enhancement, refactorize

#1513 MOdificacion loanForm
  app/Http/Requests/LoanForm.php
Labels: validation

#1515 Observadores tabla aid contributions
  app/AidContribution.php
  app/Observers/AidContributionObserver.php
  app/Providers/AidContributionServiceProvider.php
  app/Providers/AppServiceProvider.php
  app/Record.php
  config/app.php
  config/translations.php
  database/seeds/RecordTypeNameSeeder.php
Labels: enhancement

#1516 adicion de validacion de remake_loan_id cuando se envia 0
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/LoanForm.php
Labels: validation

#1517 Correccion bug al actualizar datos de personal de referencia
  app/Http/Requests/PersonalReferenceForm.php
  app/Observers/LoanObserver.php
Labels: bug

#1520 Correccion calculo liq
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug

#1523 Metodo para realizar Busqueda de un registro del ajuste de una contribucion por el ID
  app/Http/Controllers/Api/V1/LoanContributionAdjustController.php
  routes/api.php
  storage/responses/loan_contribution_adjust/show.200.json
Labels: refactorize

#1553 pago excesivo
  app/Loan.php
Labels: bug

#1556 adicion de current tiket todas las modalidades metodo contributions
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#1563 Validacion loan y creacion de campos para direcciones y global parameter
  app/Address.php
  app/Http/Requests/LoanForm.php
  database/migrations/2019_10_21_112920_add_geolocation_to_addresses_table.php
  database/migrations/2019_10_21_121445_modify_for_cascade_delete_on_addressables_table.php
  database/migrations/2019_11_06_094202_create_loan_global_parameters_table.php
  database/seeds/LoanGlobalParameterSeeder.php
  storage/responses/loan_global_parameter/show.200.json
Labels: database, validation

#1564 creacion de observers en el record de LoanCotributionAdjust
  app/LoanContributionAdjust.php
  app/Observers/LoanContributionAdjustObserver.php
  app/Providers/AppServiceProvider.php
  app/Providers/LoanContributionAdjustModelServiceProvider.php
  app/Record.php
  config/app.php
  database/seeds/RecordTypeNameSeeder.php
Labels: enhancement

#1566 Ajuste del formulario de Calificación para agregar Datos de la boleta…
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#1567 Ajuste del formulario de calificación para añadir afiliado en comisión
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/forms/qualification_form.blade.php
  routes/api.php
Labels: bug, refactorize

#1570 Ajuste de contrbuciones
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#1571 codigo y kardex
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  resources/views/loan/payments/payment_kardex.blade.php
Labels: enhancement

#1572 colocar el codigo del remake sin actualizar
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#1574 alerta afiliado
  app/Http/Controllers/Api/V1/AffiliateController.php
  routes/api.php
  storage/responses/affiliate/verify_affiliate_spouse.200.json
Labels: enhancement

#1580 Creación del de nuevo campo max_days_interest en en la tabla loan_glo…
  app/Http/Controllers/Api/V1/LoanGlobalParameterController.php
  app/LoanGlobalParameter.php
  database/migrations/2019_11_06_094202_create_loan_global_parameters_table.php
  database/seeds/LoanGlobalParameterSeeder.php
Labels: enhancement

#1582 Modificacion numero de meses
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: refactorize

#1586 seeder hipotecario 3 ballots
  database/seeds/LoanStructureSeeder.php
Labels: database

#1585 porcentajes
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: enhancement

#1589 Ajuste de formulario de amortización de cuota
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  resources/views/loan/payments/payment_loan.blade.php
Labels: refactorize

#1590 Etiqueta sismu, y correccion de etiqueas, silenciar onservador evento
  app/Http/Controllers/Api/V1/LoanController.php
  app/Observers/LoanObserver.php
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/TagSeeder.php
Labels: enhancement, refactorize, validation

#1593 agrego parametros globales para refi
  database/migrations/2019_11_06_094202_create_loan_global_parameters_table.php
  database/seeds/LoanGlobalParameterSeeder.php
Labels: database

#1594 Ajuste de direccion en el guardado
  app/Address.php
  app/Http/Controllers/Api/V1/AddressController.php
Labels: enhancement, refactorize

#1601 Nreacion de Seeder Loan
  database/seeds/LoanDestinySeeder.php
  version-seeder.sh
Labels: refactorize

#1602 Direccion y adicion de ci expedicion NINGUNO
  app/Address.php
  app/Affiliate.php
  database/seeds/CityGeolocationSeeder.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/hypothecary.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/reprogramming.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: refactorize

#1605 Se agrega promedio de bonos y liquido al formulario de calificación
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactorize

#1607 pago con id afiliado
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/payments/payment_kardex.blade.php
Labels: bug

#1608 bug cobro
  app/Loan.php
Labels: bug

#1614 Busqueda de modalidad de prestamos para el affiliado segun ci
  app/Address.php
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
  routes/api.php
  storage/responses/affiliate/affiliate_evaluate_loans.200.json
Labels: enhancement

#1615 Creación del seeder LoanDestinyProcedureTypeSeeder
  database/seeds/LoanDestinyProcedureTypeSeeder.php
  database/seeds/LoanDestinySeeder.php
  version-seeder.sh
Labels: enhancement

#1620 Se agrega flujo para para las modalidades de prestamo en RoleSequenc…
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/RoleSequenceSeeder.php
Labels: refactorize

#1624 Cambio de campo de description a zone temporal
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/PersonalReference.php
  resources/views/loan/contracts/hypothecary.blade.php
Labels: bug

#1625 Se agrego validacion de ci a metodo seach loan
  app/Http/Controllers/Api/V1/AffiliateController.php
  storage/responses/affiliate/affiliate_evaluate_loans.200.json
Labels: validation

#1630 Creación del método validate_affiliate
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
  storage/responses/loan/affiliate_evaluate.200.json
Labels: enhancement

#1631 Cambio de flujo en el seeder AdvanceRoleSeeder, RoleSequenceSeeder
  database/seeds/AdvanceRoleSeeder.php
  database/seeds/RoleSequenceSeeder.php
Labels: refactorize

#1633 ajuste del método de validate_affiliate
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactorize

#1637 Submodalidades amortizaciones
  app/Http/Controllers/Api/V1/LoanController.php
  database/seeds/CityGeolocationSeeder.php
  database/seeds/ProcedureAmortizationSeeder.php
  database/seeds/RoleSequenceSeeder.php
  storage/responses/loan_payment/bullk_update_role.200.json
  storage/responses/procedure_type/get_modality.200.json
  storage/responses/procedure_type/show.200.json
Labels: database

#1640 mostrar la descripcion en la zona en los contratos
  app/Address.php
Labels: refactorize

#1648 modificacion de metodos
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
Labels: enhancement

#1649 adicion del objeto de modalidad con el nombre
  app/Loan.php
Labels: refactorize

#1653 Adicion de informacion en el apend data y actualizacion de documentacion
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  storage/responses/affiliate/get_loan_modality.200.json
  storage/responses/affiliate/get_loans.200.json
Labels: refactorize

#1655 Metodo para la relcion de procedures hermanos y documentacion y loan append data
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
  storage/responses/affiliate/get_loans.200.json
  storage/responses/loan/get_procedure_relation.200.json
Labels: refactorize

#1656 modificacion del metodo para obtener la modalidad
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: refactorize
