Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2022-07, with the labels that each got.

#353 Implementación de procedimientos almacenados en la elaboración del Reporte de Mora
  app/Http/Controllers/Api/V1/LoanReportController.php
  database/migrations/2022_07_07_151545_create_functions_report_loans_mora.php
  routes/api.php
Labels: enhancement

#355 anticipos afp
  resources/assets/js/components/tracing/FormTracing.vue
  resources/assets/js/components/workflow/SpecificDataLoan.vue
Labels: enhancement

#358 modificacion de contrato de anticipo afp
  resources/views/loan/contracts/advance.blade.php
Labels: refactor

#366 reporte de garantias
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: bug
