Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2022-04, with the labels that each got.

#236 ficha e historial de afiliado
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/LoanBorrower.php
  app/LoanGuarantor.php
  resources/assets/js/components/affiliate/Add.vue
  resources/assets/js/components/workflow/Add.vue
  resources/assets/js/components/workflow/SpecificDataLoan.vue
Labels: enhancement

#251 Modificación de vista de prestatario
  database/migrations/2021_07_26_220728_create_view_loan_borrower_table.php
Labels: refactor

#254 Formularios y contratos
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanBorrower.php
  app/LoanGuarantor.php
  database/migrations/2022_03_09_092255_create_loan_borrowers_table.php
  database/migrations/2022_03_22_102119_create_loan_guarantors_table.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: enhancement

#257 actualizacion de prestamos
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/Spouse.php
  resources/assets/js/components/loan/Guarantor.vue
Labels: enhancement

#261 Realizar reemplazo de variables Prestatario para el modulo de seguimiento
  resources/assets/js/components/tracing/Add.vue
  resources/assets/js/components/tracing/Dashboard.vue
  resources/assets/js/components/tracing/FormTracing.vue
Labels: refactor

#268 Refactorización Vista view_loan_amortizations
  database/migrations/2021_07_26_220728_create_view_loan_amortizations_table.php
Labels: refactor

#272 datos de prestatario y garantes en calificacion
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Http/Controllers/Api/V1/MovementFundRotatoryController.php
  app/Http/Controllers/Api/V1/VoucherController.php
  app/Loan.php
  resources/assets/js/components/workflow/SpecificDataLoan.vue
  resources/views/loan/forms/qualification_form.blade.php
Labels: enhancement, refactor

#275 arreglando código de iniciales de prestatario en cobranzas
  resources/assets/js/components/payment/AddAmortization.vue
Labels: bug

#276 modificaciones en reportes
  app/Http/Controllers/Api/V1/ImportationReportController.php
  app/Http/Controllers/Api/V1/VoucherController.php
Labels: refactor

#277 amortizaciones con prestatario
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
Labels: enhancement, refactor

#279 importacion de cobros
  app/Http/Controllers/Api/V1/ImportationController.php
  resources/assets/js/components/payment/AddAmortization.vue
Labels: refactor

#282 eliminacion de migraciones y archivos loan_affiliates
  app/Console/Commands/LoanAffiliateUpdate.php
  app/Console/Commands/LoanUpdate.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanPayment.php
  routes/api.php
Labels: refactor

#286 acta de sesion de comite
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/forms/committee_session.blade.php
  routes/api.php
Labels: enhancement

#287 documentacion de impresion de acta de comite
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/forms/committee_session.blade.php
  routes/api.php
Labels: documentation

#290 Implementado botón imprimir acta
  resources/assets/js/components/workflow/Add.vue
Labels: enhancement, refactor

#294 arreglando funcionalidad botón imprimir
  resources/assets/js/components/workflow/Add.vue
Labels: refactor

#292 actualizacion de affiliado y prestatario
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/SpouseController.php
  app/LoanGuarantor.php
Labels: enhancement, refactor

#295 Master
  app/Affiliate.php
  app/Spouse.php
Labels: enhancement, refactor

#296 garantias de evaluacion
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Loan.php
  app/LoanGuarantor.php
Labels: enhancement, refactor
