Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2023-02, with the labels that each got.

#490 modificacion contratos de anticipo
  resources/views/loan/contracts/advance.blade.php
Labels: refactor

#492 3ra modificacion de contratos de anticipos
  resources/views/loan/contracts/advance.blade.php
Labels: refactor

#499 modificacion contrato anticipos
  resources/views/loan/contracts/advance.blade.php
Labels: refactor

#491 Implementación de Colas para el envío de notificaciones mediante SMS
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/SMSController.php
  app/Jobs/ProcessNotificationSMS.php
Labels: enhancement, refactor

#507 agregando configuración mysql
  config/database.php
Labels: refactor

#536 Implementación de migraciones y seeders para seguimiento en mora, closed #522, closed #523
  app/Loan.php
  app/LoanTracking.php
  app/LoanTrackingType.php
  app/User.php
  database/migrations/2023_02_23_170242_create_loan_tracking_types_table.php
  database/migrations/2023_02_23_174951_create_loan_trackings_table.php
  database/seeds/LoanTrackingTypeSeeder.php
Labels: enhancement

#539 Agregando mensaje de texto SMS para regionales
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactor

#542 Contratos Largo Plazo,activo,1gar,disponibilidad,comision,afp,senasir 1ra Version
  resources/views/loan/contracts/long.blade.php
Labels: refactor

#543 Controlador para la tabla loan_tracking
  app/Http/Controllers/Api/V1/LoanTrackingController.php
  app/LoanTracking.php
Labels: enhancement

#545 reporte de seguimiento de mora, adicion de permisos y documentacion
  app/Http/Controllers/Api/V1/LoanTrackingController.php
  database/seeds/LoanTrackingPermissionSeeder.php
  resources/views/loan/tracking/delay_tracking.blade.php
  routes/api.php
  storage/responses/delay_tracking_loan/print.200.json
Labels: enhancement

#546 arreglando mensaje de SMS sin tíldes
  app/Http/Controllers/Api/V1/LoanController.php
Labels: hotfix

#548 Contratos cortos plazos v4
  resources/views/loan/contracts/short.blade.php
Labels: enhancement

#551 Contratos largos plazos v2
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/long.blade.php
Labels: enhancement

#554 adicion de records de seguimiento de mora
  app/Observers/LoanTrackingObserver.php
  app/Providers/LoanTrackingServiceProvider.php
  config/app.php
Labels: enhancement

#556 Contratos refinanciamiento largos plazos v1
  resources/views/loan/contracts/long.blade.php
Labels: enhancement

#553 Implementación de crud para seguimiento de mora
  app/Http/Controllers/Api/V1/LoanTrackingController.php
  app/Loan.php
  app/LoanTracking.php
  routes/api.php
  storage/responses/delay_tracking_loan/destroy.200.json
  storage/responses/delay_tracking_loan/get_loan_trackings_types.200.json
  storage/responses/delay_tracking_loan/index.200.json
  storage/responses/delay_tracking_loan/show.200.json
  storage/responses/delay_tracking_loan/store.201.json
  storage/responses/delay_tracking_loan/update.200.json
Labels: enhancement

#565 contratos refinanciamiento largos plazos v2
  resources/views/loan/contracts/long.blade.php
Labels: enhancement

#568 agregando lógica de último registro
  app/Http/Controllers/Api/V1/LoanTrackingController.php
Labels: enhancement

#571 refinanciamientos cortos y largos plazos
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: enhancement

#572 contratos refinanciamiento largo plazo observacion
  resources/views/loan/contracts/long.blade.php
Labels: enhancement
