Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2023-03, with the labels that each got.

#569 agregando documentación del campo is_last_loan_tracking
  storage/responses/delay_tracking_loan/index.200.json
Labels: documentation

#576 arreglando documentación y refactorizando formato de repuesta en las …
  app/Http/Controllers/Api/V1/LoanTrackingController.php
  storage/responses/delay_tracking_loan/destroy.200.json
  storage/responses/delay_tracking_loan/show.200.json
  storage/responses/delay_tracking_loan/update.200.json
Labels: documentation, refactor

#563 cambiando a mayúsculas el mensaje de SMS
  app/Http/Controllers/Api/V1/LoanController.php
Labels: hotfix

#578 contract refinanciamiento corto plazo disp
  resources/views/loan/contracts/short.blade.php
Labels: bug

#580 cambiando formato de respuesta del método index, CRUD seguimiento de …
  app/Http/Controllers/Api/V1/LoanTrackingController.php
  storage/responses/delay_tracking_loan/index.200.json
Labels: refactor

#584 impresión de certificado de devolución a garante
  app/Http/Controllers/Api/V1/LoanCertificationController.php
  database/seeds/LoanCertificationPermissionSeeder.php
  resources/views/loan/certification/loan_certification.blade.php
  routes/api.php
  storage/responses/warranty_discount_certification/print.200.json
Labels: enhancement

#586 Creación del método default_alert_date_import para el envió de fecha de actualización considerado por cobranza
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: enhancement, refactor

#589 agregando validación de no nulo a la impresión de certificación de de…
  resources/views/loan/certification/loan_certification.blade.php
Labels: refactor

#598 Modificar codigo ante la depreciacion de v-text
  resources/assets/js/components/payment/HistoryPayments.vue
  resources/assets/js/components/payment/Kardex.vue
  resources/assets/js/components/payment/List.vue
  resources/assets/js/components/payment/ListPaymentGenerate.vue
  resources/assets/js/components/payment/LoansGenerateIndex.vue
  resources/assets/js/components/tracing/ListTracingLoans.vue
  resources/assets/js/components/treasury/ListVouchers.vue
  resources/assets/js/components/workflow/List.vue
Labels: refactor

#600 Certificacion garantia
  resources/assets/js/components/payment/Kardex.vue
  resources/assets/js/components/workflow/Add.vue
Labels: enhancement

#602 Adición de observaciones del afiliado
  resources/assets/js/components/affiliate/ObservationAffiliate.vue
  resources/assets/js/components/affiliate/ObserverAffiliate.vue
Labels: enhancement

#609 parametro global segun creacion o nuevo reglamento
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
  app/LoanPayment.php
  app/LoanProcedure.php
Labels: refactor

#612 Ajustes
  resources/assets/js/components/affiliate/Add.vue
  resources/assets/js/components/affiliate/ObservationAffiliate.vue
  resources/assets/js/components/tracing/Add.vue
  resources/assets/js/components/workflow/Dashboard.vue
Labels: refactor

#614 corrección en la eliminación de obs
  app/Http/Controllers/Api/V1/AffiliateObservationController.php
  app/Http/Requests/ObservationForm.php
Labels: refactor
