Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2023-07, with the labels that each got.

#635 Arreglando el bug de nombres que empiezan con la letra ñ, en las band…
  app/LoanBorrower.php
Labels: bug

#638 Quitando lugar de expedición de contratos y formularios de solicitud
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/reprogramming.blade.php
  resources/views/loan/contracts/short.blade.php
  resources/views/loan/forms/request_advance_form.blade.php
  resources/views/loan/forms/request_form.blade.php
  resources/views/partials/footer.blade.php
Labels: refactor

#648 ciudad de expedicion en reporte de solicitud de descuentos
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: enhancement

#649 bug reporte de mora parcial
  app/Loan.php
  database/migrations/2022_07_07_151545_create_functions_report_loans_mora.php
Labels: bug
