Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2024-07, with the labels that each got.

#745 parametrizacion de formula
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/LoanGlobalParameter.php
  app/LoanInterest.php
  app/LoanPayment.php
  database/migrations/2024_06_28_175813_add_calculation_parameters_columns_to_loans_global_parameters_table.php.php
Labels: enhancement

#746 plazo de prestamo en meses
  database/migrations/2024_07_04_111513_add_loan_month_term_column_to_loan_modality_parameters_table.php
Labels: enhancement

#747 Seed Actualización Base de Datos Segun Propuesta Reglamento 2024 PARTE 1
  database/seeds/UpdateNewReglament2024Part1.php
Labels: new

#750 Seed Actualización Base de Datos Segun Propuesta Reglamento 2024 parte 2
  app/ProcedureRequirement.php
  database/seeds/UpdateNewReglament2024Part1.php
  database/seeds/UpdateNewReglament2024Part2.php
Labels: refactor

#751 plan de pagos prestamos estacionales
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanModalityParameter.php
Labels: enhancement

#752 parametrización del plazo
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/LoanInterest.php
Labels: enhancement

#757 Ruta para la creación de Prestamos segun Propuesta de Reglamento 2024
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/ProcedureTypeController.php
  routes/api.php
Labels: new

#758 parametro en interes extra plan de pagos
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#760 Ajuste Ruta para obtencion de modulos segun tipo
  app/Http/Controllers/Api/V1/ProcedureTypeController.php
  routes/api.php
Labels: refactor

#762 Seed, Actualizacion de adición de requerimiento a submodalides de préstamos segun propuesta de reglamento 2024 #755
  database/seeds/UpdateNewReglament2024Part1.php
  database/seeds/UpdateNewReglament2024Part2.php
  database/seeds/UpdateRequirementsReglament2024.php
Labels: refactor

#763 generacion plan de pagos y cobros prestamos estacionales
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
Labels: enhancement

#766 amortizacion por prestamo estacional
  database/seeds/AmortizationSeasonTypeSeeder.php
Labels: enhancement

#768 Modificación Ruta para Obtener la submodalidad de Refinanciamiento o …
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactor

#769 bug prestamos 4 trimestre
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#771 bug prestamos 4 trimestre
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#773 Ajuste y Elaboración para el contrato de prestamos por fondo de retiro
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/ProcedureModalityController.php
  database/seeds/UpdateNewReglament2024Part1.php
  resources/views/loan/contracts/retirement_fund.blade.php
  routes/api.php
Labels: refactor, new

#775 bug parametrización de la formula refinanciamientos
  app/Loan.php
Labels: bug

#776 bug conteo de dias extra plan de pagos estacional
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#777 garantia de fondo de retiro
  app/LoanGuaranteeRetirementFund.php
  database/migrations/2024_07_26_161520_create_loan_guarantee_retirement_fund_table.php
Labels: enhancement

#779 Ruta para guardar datos de garantia para prestamos por fondo de retiro
  app/Http/Controllers/Api/V1/LoanController.php
Labels: refactor

#782 Correciones al contrato de modalidad fondo de retiro
  resources/views/loan/contracts/retirement_fund.blade.php
Labels: enhancement

#783 tabla de promedios de fondo de retiro por grado y seeder
  app/Degree.php
  app/RetirementFundAverage.php
  database/migrations/2024_07_29_095020_create_retirement_fund_averages_table.php
  database/migrations/2024_07_29_095220_create_loan_guarantee_retirement_fund_table.php
  database/migrations/2024_07_29_122020_add_is_active_degree_table.php
  database/seeds/RetirementFundSAveragesSeeder.php
Labels: enhancement

#784 promedio fondo de retiro en afiliado
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  routes/api.php
Labels: enhancement

#788 Ajustes para la automatización de tabla promedio de fondo de retiro para prestamos de Fondo de Retiro
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  app/LoanGuaranteeRetirementFund.php
  app/RetirementFundAverage.php
  database/seeds/UpdateNewReglament2024Part1.php
  database/seeds/UpdateRequirementsReglament2024.php
  resources/views/loan/forms/qualification_form.blade.php
Labels: enhancement, refactor, new

#790 Procedimiento para validad al afiliado con la submodalidad selecionada
  app/Http/Controllers/Api/V1/AffiliateController.php
  database/seeds/UpdateNewReglament2024Part1.php
  routes/api.php
Labels: new

#793 cobertura de prestamos con fondo de retiro
  app/Http/Controllers/Api/V1/CalculatorController.php
  resources/assets/js/components/affiliate/Spouse.vue
Labels: enhancement

#795 completado de seeder, grado inactivo y porcentaje de fondo de retiro
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/DegreeController.php
  database/seeds/RetirementFundSAveragesSeeder.php
Labels: enhancement

#796 Correciones para generación de contrato para fondo de retiro
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/contracts/retirement_fund.blade.php
Labels: enhancement

#798 ajustes para préstamos estacionales en formularios de solicitud y cal…
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/forms/qualification_form.blade.php
  resources/views/loan/forms/request_form.blade.php
Labels: new

#799 validación de fondo de retiro
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: enhancement
