Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2024-10, with the labels that each got.

#911 monto sugerido v3
  app/LoanModalityParameter.php
Labels: enhancement

#912 Modificación del texto en el mensaje SMS enviado al realizar un desem…
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#914 correcion de monto sugerido
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug

#915 validación de observaciones al afiliado
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#921 Cobranzas dev
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#922 formularios solicitud, calificacion y contratos con plazo en singular
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/seasonal.blade.php
  resources/views/loan/contracts/short.blade.php
  resources/views/loan/forms/qualification_form.blade.php
  resources/views/loan/forms/request_form.blade.php
Labels: bug

#925 Cobranzas dev to testing
  resources/views/loan/contracts/short.blade.php
Labels: bug

#930 importación masiva de prestamos estacionales v1
  app/Affiliate.php
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  database/migrations/2024_10_15_084110_create_loan_payment_copy_estacionales_table.php
  database/migrations/2024_10_15_095026_create_loan_payment_group_estacionales_table.php
  resources/assets/js/components/payment/ImportExportPayment.vue
  routes/api.php
Labels: enhancement

#929 Reporte de prestamos estacionales para solicitud a COMPLEMENTO ECONOMICO
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: new

#932 regeneración de planes de pagos
  app/Http/Controllers/Api/V1/LoanController.php
  resources/assets/js/components/tracing/ListTracingLoans.vue
  routes/api.php
Labels: enhancement

#933 Cambios en texto y corrección de bug
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/ImportationReportController.php
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  app/Loan.php
Labels: bug, enhancement
