Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2024-09, with the labels that each got.

#880 adicion refinanciamiento para largo plazo afp
  app/Http/Controllers/Api/V1/LoanController.php
Labels: new

#883 adicion refinanciamiento del refinanciamiento para largo plazo afp
  app/Http/Controllers/Api/V1/LoanController.php
Labels: new

#890 loan_month_term en el modelo loan
  app/Loan.php
Labels: bug

#891 resolución del bug de los plazos
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: bug

#894 bug pago prestamos estacionales
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#899 Actualizacion de Promedio por Fondo de Retiro
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanBorrower.php
Labels: bug

#898 Comentar - Actualizacion de Promedio por Fondo de Retiro
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanBorrower.php
Labels: duplicate

#902 Desarrollo de Reporte de préstamos que incumplieron el plan de pagos
  app/Http/Controllers/Api/V1/LoanReportController.php
  database/migrations/2024_09_13_114724_add_procedure_loans_partial_payments.php
  resources/assets/js/components/reports/Reports.vue
  routes/api.php
Labels: new

#904 plan de pagos a 1 cuota
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#906 cobros de prestamos a 1 cuota
  app/Loan.php
Labels: enhancement

#909 reporte de afiliados con observaciones
  app/Http/Controllers/Api/V1/LoanReportController.php
  resources/assets/js/components/reports/Reports.vue
  routes/api.php
Labels: enhancement
