Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2024-04, with the labels that each got.

#696 Cambio de Amortizacion con Beneficios
  resources/assets/js/components/payment/AddAmortization.vue
Labels: enhancement

#698 Res. Ticket Modificacion Rep. Amortizacion en efectivo y desposito en cuenta
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
  app/Http/Controllers/Api/V1/VoucherController.php
  app/Loan.php
Labels: enhancement

#702 COLUMNA NUP -> Rep. estado en mora, en mora, desc. por garantia y Días transc…
  app/Http/Controllers/Api/V1/LoanReportController.php
  database/migrations/2024_04_10_102745_replace_functions_loans_mora_data.php
Labels: refactor

#708 Reporte Prestamos Días Transcurridos desde el ultimo pago v2
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Loan.php
Labels: refactor

#710 Reporte Prestamos Días Transcurridos v2 mod
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: enhancement

#714 Restricion de afiliado observado para garantias
  app/Http/Controllers/Api/V1/AffiliateController.php
  resources/assets/js/components/affiliate/ObservationAffiliate.vue
Labels: enhancement

#718 actualización de documentos en lote
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
Labels: enhancement

#720 correccion de validación
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#721 correccion de documentos validados
  app/Loan.php
Labels: enhancement
