Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2024-05, with the labels that each got.

#725 Reporte Amortización por complemento y fondo de retiro actualización
  app/Http/Controllers/Api/V1/LoanPaymentReportController.php
Labels: bug

#726 actualización de saldo SISMU
  app/Http/Controllers/Api/V1/SismuController.php
  resources/assets/js/components/sismu/Index.vue
  resources/assets/js/menu.json
  resources/assets/js/routes.js
  routes/api.php
Labels: enhancement

#729 nuevo Reporte de Ingresos
  app/Http/Controllers/Api/V1/LoanReportController.php
  resources/assets/js/components/reports/Reports.vue
  routes/api.php
Labels: new
