Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2024-08, with the labels that each got.

#800 Ajuste al contrato para prestamos y refinanciamiento a largo plaza pa…
  resources/views/loan/contracts/long.blade.php
Labels: enhancement

#804 bug monto maximo en fondo de retiro
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: bug

#808 validación de nuevo tipo de ajuste
  app/Http/Requests/LoanContributionAdjustForm.php
Labels: enhancement

#810 Ajustes los nombres de los documentos para requisitos de prestamos pa…
  database/seeds/UpdateNewReglament2024Part2.php
Labels: enhancement

#811 corrección del seeder de modalidades
  database/seeds/RoleSequence2024Seeder.php
Labels: bug

#814 Ajuste y Refactorizacion para contratos de Préstamos
  app/Http/Controllers/Api/V1/LoanController.php
  database/seeds/UpdateRequirementsReglament2024.php
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/seasonal.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: enhancement, refactor, new

#820 Ajustes para a los requerimientos para fundo de retirp
  app/Http/Controllers/Api/V1/LoanController.php
  app/Loan.php
  database/seeds/UpdateNewReglament2024Part1.php
  resources/views/loan/contracts/retirement_fund.blade.php
Labels: enhancement

#821 Impresión de Boleta de Pago importada de planilla-Comando
  app/Contribution.php
  app/Http/Controllers/Api/V1/ContributionController.php
  resources/views/contribution/contribution_voucher.blade.php
  routes/api.php
Labels: new

#823 Ajuste porcentaje limite de endeudamiento garantes seeders
  database/seeds/UpdateNewReglament2024Part1.php
Labels: new

#828 Ajuste seed para préstamo estacional, "autorizado po"
  database/seeds/UpdateNewReglament2024Part1.php
Labels: new

#831 ajuste sedder
  database/seeds/UpdateNewReglament2024Part2.php
Labels: bug

#834 Ajuste sedder shortened largo plazo oportuno
  database/seeds/UpdateNewReglament2024Part1.php
Labels: bug

#837 Quitar visibilidad en formulario de calificacion porcentaje de pago
  resources/views/loan/forms/qualification_form.blade.php
Labels: refactor

#838 evaluación de garante permitida
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: enhancement

#839 ajuste a plantillas de contratos segun nuevos requrimientos segun nota 1842
  resources/views/loan/contracts/advance.blade.php
  resources/views/loan/contracts/long.blade.php
  resources/views/loan/contracts/retirement_fund.blade.php
  resources/views/loan/contracts/short.blade.php
Labels: new

#840 bug boletas de prestamos estacionales
  app/LoanBorrower.php
Labels: bug

#843 situacion laboral frontend
  resources/assets/js/components/affiliate/Profile.vue
Labels: enhancement

#844 cambio de nombre al campo de información de disonibilidad
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Requests/AffiliateForm.php
  app/LoanBorrower.php
  database/migrations/2024_08_14_113813_add_column_work_situation_to_affiliates_table.php
  database/migrations/2024_08_14_113950_add_column_work_situation_to_loan_borrowers_table.php
  resources/assets/js/components/affiliate/Profile.vue
Labels: refactor

#845 bug rehacer prestamos estacionales
  app/LoanBorrower.php
Labels: bug

#846 eliminacion del registro de matricula y datos de disponibilidad en fo…
  resources/assets/js/components/affiliate/Profile.vue
  resources/assets/js/components/affiliate/Spouse.vue
  resources/views/loan/forms/request_form.blade.php
Labels: enhancement

#847 Ajuste contrato Estacional, nuevos requerimientos
  resources/views/loan/contracts/seasonal.blade.php
Labels: new

#848 migraciones de datos de evaluacion y adicion de los datos a respuesta
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  database/migrations/2024_08_16_143650_add_column_eval_percentage_to_loan_modality_parameters_table.php
  database/migrations/2024_08_16_143750_add_column_eval_quota_to_loan_guarantors_table.php
  routes/api.php
Labels: enhancement

#849 Ajustes para evaluacion de garantias, plantilla de contrato de reprogramacion y correcion de requisitos de beneficios
  database/seeds/UpdateNewReglament2024Part1.php
  database/seeds/UpdateNewReglament2024Part2.php
  resources/views/loan/contracts/reprogramming.blade.php
Labels: refactor

#853 porcentaje de evaluacion
  app/Http/Controllers/Api/V1/CalculatorController.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanGuaranteeRegisterController.php
  app/LoanBorrower.php
  resources/assets/js/components/loan/Guarantor.vue
Labels: enhancement

#854 Correccion de requisito --name
  database/seeds/UpdateNewReglament2024Part2.php
Labels: bug

#856 Inserción porcentaje de pago formulario de calificación
  resources/views/loan/forms/qualification_form.blade.php
Labels: bug

#858 eval_quota en evaluación de garante
  app/Http/Controllers/Api/V1/CalculatorController.php
Labels: enhancement

#860 eval_quota en modelo garantes
  app/LoanBorrower.php
  app/LoanGuarantor.php
Labels: bug

#862 Ajuste porcentaje de evaluacion al 50 para un garante
  database/seeds/UpdateNewReglament2024Part1.php
Labels: new

#869 bug firma conyugue anuente
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#874 adicion submodalidades para disponibilidad
  app/Http/Controllers/Api/V1/AffiliateController.php
Labels: new

#877 liberación del tramite
  app/Http/Controllers/Api/V1/LoanController.php
  routes/api.php
Labels: enhancement
