Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2024-12, with the labels that each got.

#938 métodos para la certificación de No Adeudo
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/loan/certification/no_debt_certification.blade.php
  routes/api.php
Labels: new

#939 bug calculo de cuota estacional
  app/Http/Controllers/Api/V1/LoanController.php
Labels: bug

#943 migración para adicionar columnas en la tabla loan_payment_periods
  database/migrations/2024_12_10_151750_add_columns_importation_quantity_and_importation_date_to_loan_payment_periods.php
Labels: enhancement

#944 importación adicional v1
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  database/migrations/2024_12_09_113310_create_loan_payment_copy_additionals_table.php
Labels: enhancement

#947 importación adicional, conteo de registros importados
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
Labels: enhancement

#948 importación adicional, barra de progreso
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: enhancement

#949 ruta de validación de importación adicional
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  routes/api.php
Labels: enhancement

#950 bug conteo en barra de progreso
  app/Http/Controllers/Api/V1/ImportationController.php
Labels: bug

#952 bug, reporte de cobros importados
  app/Http/Controllers/Api/V1/ImportationReportController.php
Labels: bug

#955 monto balance, importación adicional
  app/Http/Controllers/Api/V1/ImportationController.php
  database/migrations/2024_12_09_113310_create_loan_payment_copy_additionals_table.php
Labels: enhancement
