Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2025-02, with the labels that each got.

#986 modificación de flujos de pagos v1
  app/Helpers/Util.php
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Rules/LoanRole.php
  app/Workflow.php
  resources/assets/js/components/payment/AddAmortization.vue
  resources/assets/js/components/payment/ListPaymentGenerate.vue
  resources/assets/js/components/payment/Steps.vue
  resources/assets/js/components/tracing/ListTracingLoans.vue
  resources/assets/js/components/workflow/Add.vue
Labels: enhancement, refactor

#988 derivación de cobros
  app/Http/Controllers/Api/V1/LoanPaymentController.php
  app/Http/Requests/LoanPaymentsForm.php
Labels: enhancement

#996 Actualización de documentación respecto a Microsoft ODBC Driver, SQL …
  docs/docker/Dockerfile
  docs/docker/README.md
Labels: documentation

#999 validaciones y creación de nuevas vistas para bandeja de seguimiento
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/LoanReportController.php
  app/Http/Requests/LoanForm.php
  app/LoanPayment.php
  database/migrations/2025_02_19_094148_update_view_loan_borrower.php
  database/migrations/2025_02_19_094935_create_view_loan_guarantors_table.php
  resources/assets/js/components/tracing/ListTracingLoans.vue
  resources/assets/js/components/workflow/Add.vue
Labels: refactor

#1000 refinanciamientos y reprogramaciones
  app/Http/Controllers/Api/V1/AffiliateController.php
  app/Http/Controllers/Api/V1/ProcedureTypeController.php
  routes/api.php
Labels: enhancement

#1001 generación de planes de pago
  app/Http/Controllers/Api/V1/LoanController.php
  resources/assets/js/components/workflow/Add.vue
Labels: enhancement
