Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2025-01, with the labels that each got.

#957 corrigiendo bug de mostrar texto de plazos en formularios
  resources/views/loan/contracts/reprogramming.blade.php
  resources/views/loan/forms/qualification_form.blade.php
  resources/views/loan/payments/payment_kardex.blade.php
  resources/views/loan/payments/payment_kardex_unfolded.blade.php
  resources/views/loan/payments/payment_plan.blade.php
Labels: bug

#958 modificaciones para importación adicional
  app/Affiliate.php
  app/Http/Controllers/Api/V1/ImportationController.php
  app/Http/Controllers/Api/V1/ImportationReportController.php
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  database/migrations/2024_12_09_113310_create_loan_payment_copy_additionals_table.php
  resources/assets/js/components/affiliate/List.vue
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement

#962 columna de modalidad en reporte de ingresos
  app/Http/Controllers/Api/V1/LoanReportController.php
Labels: enhancement

#968 inhabilitación funcionalidad importacion adicional
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: wontfix

#971 listado de prestamos del afiliado
  app/Affiliate.php
  app/Http/Controllers/Api/V1/AffiliateController.php
  resources/assets/js/components/affiliate/Dashboard.vue
  routes/api.php
Labels: enhancement

#978 habilitación de importación adicional
  app/Http/Controllers/Api/V1/LoanPaymentPeriodController.php
  resources/assets/js/components/payment/ImportExportPayment.vue
Labels: enhancement
