Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT, pull requests merged in 2025-03, with the labels that each got.

#1017 modificación de interes pendiente SISMU
  app/Http/Controllers/Api/V1/SismuController.php
  routes/api.php
Labels: enhancement

#1021 refactorizacion de refinanciamientos y reprogramaciones
  app/Http/Controllers/Api/V1/LoanController.php
  app/LoanModalityParameter.php
  database/migrations/2025_03_07_160543_add_columns_refi_repro_to_loan_modality_parameters_table.php
  resources/assets/js/components/loan/Steps.vue
  routes/api.php
Labels: enhancement

#1023 validación del monto
  app/Http/Controllers/Api/V1/SismuController.php
Labels: enhancement

#1025 crud y migraciones de workflow
  app/Http/Controllers/Api/V1/WorkflowController.php
  app/Workflow.php
  database/migrations/2025_03_14_095135_add_timestamps_and_deleted_at_to_workflow_table.php
  routes/api.php
Labels: enhancement

#1026 crud de sequencia de tramites
  app/Http/Controllers/Api/V1/WfSequenceController.php
  app/Http/Controllers/Api/V1/WorkflowController.php
  routes/api.php
Labels: enhancement

#1019 corrección para el monto de ajuste
  resources/views/loan/forms/qualification_form.blade.php
Labels: bug

#1030 actualización de saldos en prestamos
  app/Http/Controllers/Api/V1/SismuController.php
  resources/assets/js/components/sismu/Index.vue
Labels: enhancement

#1032 formulario de derivación de tramites
  app/Http/Controllers/Api/V1/LoanController.php
Labels: enhancement

#1033 Cobranzas dev
  app/Http/Controllers/Api/V1/LoanController.php
  app/Http/Controllers/Api/V1/ProcedureModalityController.php
  app/Http/Controllers/Api/V1/WfSequenceController.php
  app/Http/Controllers/Api/V1/WorkflowController.php
  app/Observers/WorkflowObserver.php
  app/Providers/WorkflowModelServiceProvider.php
  app/Workflow.php
  config/app.php
  database/migrations/2025_03_14_095135_add_timestamps_and_deleted_at_to_workflow_table.php
  routes/api.php
Labels: enhancement

#1034 devolución de sequencias ordenadas
  app/Http/Controllers/Api/V1/WfSequenceController.php
  app/WfSequence.php
Labels: enhancement

#1036 modalidades en formulario de derivación
  app/Http/Controllers/Api/V1/LoanController.php
  resources/views/flow/bulk_flow_procedures.blade.php
  resources/views/flow/tbody/loan.blade.php
  resources/views/flow/thead/loan.blade.php
Labels: enhancement

#1038 asignación de flujo a una modalidad
  app/Http/Controllers/Api/V1/ProcedureModalityController.php
  app/Http/Controllers/Api/V1/WfSequenceController.php
  routes/api.php
Labels: enhancement

#1039 filtrado de areas
  app/Http/Controllers/Api/V1/WfStatesController.php
  routes/api.php
Labels: enhancement

#1045 obtencion de modalidades para prestamos y amortizaciones
  app/Http/Controllers/Api/V1/ProcedureTypeController.php
  routes/api.php
Labels: enhancement

#1046 validacion en eliminación de flujos
  app/Http/Controllers/Api/V1/WorkflowController.php
  app/ProcedureModality.php
  app/Workflow.php
Labels: enhancement

#1049 eliminación del antiguo workflow
  public/docs/collection.json
  resources/assets/js/components/procedure_type/Workflow.vue
  resources/assets/js/menu.json
  resources/assets/js/routes.js
  routes/api.php
Labels: refactor
